//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSCustomerBase.LoginService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usp_GetUserDetailByUserName_Result", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SmileSCustomerBase.LoginService.LoginDetail))]
    public partial class usp_GetUserDetailByUserName_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        private int User_IDField;
        
        private System.Nullable<int> Person_IDField;
        
        private System.Nullable<int> Employee_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeePositionDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeTeamDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentDetailField;
        
        private System.Nullable<int> EmployeeTeam_IDField;
        
        private System.Nullable<int> Branch_IDField;
        
        private System.Nullable<int> Department_IDField;
        
        private System.Nullable<int> EmployeePosition_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int User_ID {
            get {
                return this.User_IDField;
            }
            set {
                if ((this.User_IDField.Equals(value) != true)) {
                    this.User_IDField = value;
                    this.RaisePropertyChanged("User_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<int> Person_ID {
            get {
                return this.Person_IDField;
            }
            set {
                if ((this.Person_IDField.Equals(value) != true)) {
                    this.Person_IDField = value;
                    this.RaisePropertyChanged("Person_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> Employee_ID {
            get {
                return this.Employee_IDField;
            }
            set {
                if ((this.Employee_IDField.Equals(value) != true)) {
                    this.Employee_IDField = value;
                    this.RaisePropertyChanged("Employee_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string EmployeePositionDetail {
            get {
                return this.EmployeePositionDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeePositionDetailField, value) != true)) {
                    this.EmployeePositionDetailField = value;
                    this.RaisePropertyChanged("EmployeePositionDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string EmployeeTeamDetail {
            get {
                return this.EmployeeTeamDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeTeamDetailField, value) != true)) {
                    this.EmployeeTeamDetailField = value;
                    this.RaisePropertyChanged("EmployeeTeamDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string BranchDetail {
            get {
                return this.BranchDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchDetailField, value) != true)) {
                    this.BranchDetailField = value;
                    this.RaisePropertyChanged("BranchDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string DepartmentDetail {
            get {
                return this.DepartmentDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentDetailField, value) != true)) {
                    this.DepartmentDetailField = value;
                    this.RaisePropertyChanged("DepartmentDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.Nullable<int> EmployeeTeam_ID {
            get {
                return this.EmployeeTeam_IDField;
            }
            set {
                if ((this.EmployeeTeam_IDField.Equals(value) != true)) {
                    this.EmployeeTeam_IDField = value;
                    this.RaisePropertyChanged("EmployeeTeam_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.Nullable<int> Branch_ID {
            get {
                return this.Branch_IDField;
            }
            set {
                if ((this.Branch_IDField.Equals(value) != true)) {
                    this.Branch_IDField = value;
                    this.RaisePropertyChanged("Branch_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public System.Nullable<int> Department_ID {
            get {
                return this.Department_IDField;
            }
            set {
                if ((this.Department_IDField.Equals(value) != true)) {
                    this.Department_IDField = value;
                    this.RaisePropertyChanged("Department_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public System.Nullable<int> EmployeePosition_ID {
            get {
                return this.EmployeePosition_IDField;
            }
            set {
                if ((this.EmployeePosition_IDField.Equals(value) != true)) {
                    this.EmployeePosition_IDField = value;
                    this.RaisePropertyChanged("EmployeePosition_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginDetail", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class LoginDetail : SmileSCustomerBase.LoginService.usp_GetUserDetailByUserName_Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RolesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Roles {
            get {
                return this.RolesField;
            }
            set {
                if ((object.ReferenceEquals(this.RolesField, value) != true)) {
                    this.RolesField = value;
                    this.RaisePropertyChanged("Roles");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuList", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MenuList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MenuIdField;
        
        private System.Nullable<int> MainMenuIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string projectnameField;
        
        private System.Nullable<int> SortOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ControllerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IconClassNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MenuId {
            get {
                return this.MenuIdField;
            }
            set {
                if ((this.MenuIdField.Equals(value) != true)) {
                    this.MenuIdField = value;
                    this.RaisePropertyChanged("MenuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<int> MainMenuId {
            get {
                return this.MainMenuIdField;
            }
            set {
                if ((this.MainMenuIdField.Equals(value) != true)) {
                    this.MainMenuIdField = value;
                    this.RaisePropertyChanged("MainMenuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string projectname {
            get {
                return this.projectnameField;
            }
            set {
                if ((object.ReferenceEquals(this.projectnameField, value) != true)) {
                    this.projectnameField = value;
                    this.RaisePropertyChanged("projectname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> SortOrder {
            get {
                return this.SortOrderField;
            }
            set {
                if ((this.SortOrderField.Equals(value) != true)) {
                    this.SortOrderField = value;
                    this.RaisePropertyChanged("SortOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Detail {
            get {
                return this.DetailField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailField, value) != true)) {
                    this.DetailField = value;
                    this.RaisePropertyChanged("Detail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Controller {
            get {
                return this.ControllerField;
            }
            set {
                if ((object.ReferenceEquals(this.ControllerField, value) != true)) {
                    this.ControllerField = value;
                    this.RaisePropertyChanged("Controller");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Action {
            get {
                return this.ActionField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionField, value) != true)) {
                    this.ActionField = value;
                    this.RaisePropertyChanged("Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string IconClassName {
            get {
                return this.IconClassNameField;
            }
            set {
                if ((object.ReferenceEquals(this.IconClassNameField, value) != true)) {
                    this.IconClassNameField = value;
                    this.RaisePropertyChanged("IconClassName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginService.SmileSLoginServiceSoap")]
    public interface SmileSLoginServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        SmileSCustomerBase.LoginService.HelloWorldResponse HelloWorld(SmileSCustomerBase.LoginService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<SmileSCustomerBase.LoginService.HelloWorldResponse> HelloWorldAsync(SmileSCustomerBase.LoginService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        SmileSCustomerBase.LoginService.LoginResponse Login(SmileSCustomerBase.LoginService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<SmileSCustomerBase.LoginService.LoginResponse> LoginAsync(SmileSCustomerBase.LoginService.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLoginDetail", ReplyAction="*")]
        SmileSCustomerBase.LoginService.GetLoginDetailResponse GetLoginDetail(SmileSCustomerBase.LoginService.GetLoginDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLoginDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<SmileSCustomerBase.LoginService.GetLoginDetailResponse> GetLoginDetailAsync(SmileSCustomerBase.LoginService.GetLoginDetailRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResetPassword", ReplyAction="*")]
        SmileSCustomerBase.LoginService.ResetPasswordResponse ResetPassword(SmileSCustomerBase.LoginService.ResetPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResetPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<SmileSCustomerBase.LoginService.ResetPasswordResponse> ResetPasswordAsync(SmileSCustomerBase.LoginService.ResetPasswordRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePassword", ReplyAction="*")]
        SmileSCustomerBase.LoginService.ChangePasswordResponse ChangePassword(SmileSCustomerBase.LoginService.ChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<SmileSCustomerBase.LoginService.ChangePasswordResponse> ChangePasswordAsync(SmileSCustomerBase.LoginService.ChangePasswordRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePassword_SSS", ReplyAction="*")]
        SmileSCustomerBase.LoginService.ChangePassword_SSSResponse ChangePassword_SSS(SmileSCustomerBase.LoginService.ChangePassword_SSSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePassword_SSS", ReplyAction="*")]
        System.Threading.Tasks.Task<SmileSCustomerBase.LoginService.ChangePassword_SSSResponse> ChangePassword_SSSAsync(SmileSCustomerBase.LoginService.ChangePassword_SSSRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMenuList", ReplyAction="*")]
        SmileSCustomerBase.LoginService.GetMenuListResponse GetMenuList(SmileSCustomerBase.LoginService.GetMenuListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMenuList", ReplyAction="*")]
        System.Threading.Tasks.Task<SmileSCustomerBase.LoginService.GetMenuListResponse> GetMenuListAsync(SmileSCustomerBase.LoginService.GetMenuListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public SmileSCustomerBase.LoginService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SmileSCustomerBase.LoginService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmileSCustomerBase.LoginService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SmileSCustomerBase.LoginService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public SmileSCustomerBase.LoginService.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(SmileSCustomerBase.LoginService.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmileSCustomerBase.LoginService.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(SmileSCustomerBase.LoginService.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SmileSCustomerBase.LoginService.LoginDetail LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(SmileSCustomerBase.LoginService.LoginDetail LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLoginDetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLoginDetail", Namespace="http://tempuri.org/", Order=0)]
        public SmileSCustomerBase.LoginService.GetLoginDetailRequestBody Body;
        
        public GetLoginDetailRequest() {
        }
        
        public GetLoginDetailRequest(SmileSCustomerBase.LoginService.GetLoginDetailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLoginDetailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public GetLoginDetailRequestBody() {
        }
        
        public GetLoginDetailRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLoginDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLoginDetailResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmileSCustomerBase.LoginService.GetLoginDetailResponseBody Body;
        
        public GetLoginDetailResponse() {
        }
        
        public GetLoginDetailResponse(SmileSCustomerBase.LoginService.GetLoginDetailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLoginDetailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SmileSCustomerBase.LoginService.LoginDetail GetLoginDetailResult;
        
        public GetLoginDetailResponseBody() {
        }
        
        public GetLoginDetailResponseBody(SmileSCustomerBase.LoginService.LoginDetail GetLoginDetailResult) {
            this.GetLoginDetailResult = GetLoginDetailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResetPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResetPassword", Namespace="http://tempuri.org/", Order=0)]
        public SmileSCustomerBase.LoginService.ResetPasswordRequestBody Body;
        
        public ResetPasswordRequest() {
        }
        
        public ResetPasswordRequest(SmileSCustomerBase.LoginService.ResetPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ResetPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public ResetPasswordRequestBody() {
        }
        
        public ResetPasswordRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResetPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResetPasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmileSCustomerBase.LoginService.ResetPasswordResponseBody Body;
        
        public ResetPasswordResponse() {
        }
        
        public ResetPasswordResponse(SmileSCustomerBase.LoginService.ResetPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ResetPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ResetPasswordResult;
        
        public ResetPasswordResponseBody() {
        }
        
        public ResetPasswordResponseBody(bool ResetPasswordResult) {
            this.ResetPasswordResult = ResetPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePassword", Namespace="http://tempuri.org/", Order=0)]
        public SmileSCustomerBase.LoginService.ChangePasswordRequestBody Body;
        
        public ChangePasswordRequest() {
        }
        
        public ChangePasswordRequest(SmileSCustomerBase.LoginService.ChangePasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangePasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string newPassword;
        
        public ChangePasswordRequestBody() {
        }
        
        public ChangePasswordRequestBody(string username, string newPassword) {
            this.username = username;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmileSCustomerBase.LoginService.ChangePasswordResponseBody Body;
        
        public ChangePasswordResponse() {
        }
        
        public ChangePasswordResponse(SmileSCustomerBase.LoginService.ChangePasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangePasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ChangePasswordResult;
        
        public ChangePasswordResponseBody() {
        }
        
        public ChangePasswordResponseBody(bool ChangePasswordResult) {
            this.ChangePasswordResult = ChangePasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePassword_SSSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePassword_SSS", Namespace="http://tempuri.org/", Order=0)]
        public SmileSCustomerBase.LoginService.ChangePassword_SSSRequestBody Body;
        
        public ChangePassword_SSSRequest() {
        }
        
        public ChangePassword_SSSRequest(SmileSCustomerBase.LoginService.ChangePassword_SSSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangePassword_SSSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string newPassword;
        
        public ChangePassword_SSSRequestBody() {
        }
        
        public ChangePassword_SSSRequestBody(string username, string newPassword) {
            this.username = username;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePassword_SSSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePassword_SSSResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmileSCustomerBase.LoginService.ChangePassword_SSSResponseBody Body;
        
        public ChangePassword_SSSResponse() {
        }
        
        public ChangePassword_SSSResponse(SmileSCustomerBase.LoginService.ChangePassword_SSSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangePassword_SSSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ChangePassword_SSSResult;
        
        public ChangePassword_SSSResponseBody() {
        }
        
        public ChangePassword_SSSResponseBody(bool ChangePassword_SSSResult) {
            this.ChangePassword_SSSResult = ChangePassword_SSSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMenuListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMenuList", Namespace="http://tempuri.org/", Order=0)]
        public SmileSCustomerBase.LoginService.GetMenuListRequestBody Body;
        
        public GetMenuListRequest() {
        }
        
        public GetMenuListRequest(SmileSCustomerBase.LoginService.GetMenuListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMenuListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string projectName;
        
        public GetMenuListRequestBody() {
        }
        
        public GetMenuListRequestBody(string username, string projectName) {
            this.username = username;
            this.projectName = projectName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMenuListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMenuListResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmileSCustomerBase.LoginService.GetMenuListResponseBody Body;
        
        public GetMenuListResponse() {
        }
        
        public GetMenuListResponse(SmileSCustomerBase.LoginService.GetMenuListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMenuListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SmileSCustomerBase.LoginService.MenuList[] GetMenuListResult;
        
        public GetMenuListResponseBody() {
        }
        
        public GetMenuListResponseBody(SmileSCustomerBase.LoginService.MenuList[] GetMenuListResult) {
            this.GetMenuListResult = GetMenuListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmileSLoginServiceSoapChannel : SmileSCustomerBase.LoginService.SmileSLoginServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmileSLoginServiceSoapClient : System.ServiceModel.ClientBase<SmileSCustomerBase.LoginService.SmileSLoginServiceSoap>, SmileSCustomerBase.LoginService.SmileSLoginServiceSoap {
        
        public SmileSLoginServiceSoapClient() {
        }
        
        public SmileSLoginServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmileSLoginServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmileSLoginServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmileSLoginServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmileSCustomerBase.LoginService.HelloWorldResponse SmileSCustomerBase.LoginService.SmileSLoginServiceSoap.HelloWorld(SmileSCustomerBase.LoginService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SmileSCustomerBase.LoginService.HelloWorldRequest inValue = new SmileSCustomerBase.LoginService.HelloWorldRequest();
            inValue.Body = new SmileSCustomerBase.LoginService.HelloWorldRequestBody();
            SmileSCustomerBase.LoginService.HelloWorldResponse retVal = ((SmileSCustomerBase.LoginService.SmileSLoginServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmileSCustomerBase.LoginService.HelloWorldResponse> SmileSCustomerBase.LoginService.SmileSLoginServiceSoap.HelloWorldAsync(SmileSCustomerBase.LoginService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmileSCustomerBase.LoginService.HelloWorldResponse> HelloWorldAsync() {
            SmileSCustomerBase.LoginService.HelloWorldRequest inValue = new SmileSCustomerBase.LoginService.HelloWorldRequest();
            inValue.Body = new SmileSCustomerBase.LoginService.HelloWorldRequestBody();
            return ((SmileSCustomerBase.LoginService.SmileSLoginServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmileSCustomerBase.LoginService.LoginResponse SmileSCustomerBase.LoginService.SmileSLoginServiceSoap.Login(SmileSCustomerBase.LoginService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public SmileSCustomerBase.LoginService.LoginDetail Login(string username, string password) {
            SmileSCustomerBase.LoginService.LoginRequest inValue = new SmileSCustomerBase.LoginService.LoginRequest();
            inValue.Body = new SmileSCustomerBase.LoginService.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            SmileSCustomerBase.LoginService.LoginResponse retVal = ((SmileSCustomerBase.LoginService.SmileSLoginServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmileSCustomerBase.LoginService.LoginResponse> SmileSCustomerBase.LoginService.SmileSLoginServiceSoap.LoginAsync(SmileSCustomerBase.LoginService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmileSCustomerBase.LoginService.LoginResponse> LoginAsync(string username, string password) {
            SmileSCustomerBase.LoginService.LoginRequest inValue = new SmileSCustomerBase.LoginService.LoginRequest();
            inValue.Body = new SmileSCustomerBase.LoginService.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((SmileSCustomerBase.LoginService.SmileSLoginServiceSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmileSCustomerBase.LoginService.GetLoginDetailResponse SmileSCustomerBase.LoginService.SmileSLoginServiceSoap.GetLoginDetail(SmileSCustomerBase.LoginService.GetLoginDetailRequest request) {
            return base.Channel.GetLoginDetail(request);
        }
        
        public SmileSCustomerBase.LoginService.LoginDetail GetLoginDetail(string username) {
            SmileSCustomerBase.LoginService.GetLoginDetailRequest inValue = new SmileSCustomerBase.LoginService.GetLoginDetailRequest();
            inValue.Body = new SmileSCustomerBase.LoginService.GetLoginDetailRequestBody();
            inValue.Body.username = username;
            SmileSCustomerBase.LoginService.GetLoginDetailResponse retVal = ((SmileSCustomerBase.LoginService.SmileSLoginServiceSoap)(this)).GetLoginDetail(inValue);
            return retVal.Body.GetLoginDetailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmileSCustomerBase.LoginService.GetLoginDetailResponse> SmileSCustomerBase.LoginService.SmileSLoginServiceSoap.GetLoginDetailAsync(SmileSCustomerBase.LoginService.GetLoginDetailRequest request) {
            return base.Channel.GetLoginDetailAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmileSCustomerBase.LoginService.GetLoginDetailResponse> GetLoginDetailAsync(string username) {
            SmileSCustomerBase.LoginService.GetLoginDetailRequest inValue = new SmileSCustomerBase.LoginService.GetLoginDetailRequest();
            inValue.Body = new SmileSCustomerBase.LoginService.GetLoginDetailRequestBody();
            inValue.Body.username = username;
            return ((SmileSCustomerBase.LoginService.SmileSLoginServiceSoap)(this)).GetLoginDetailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmileSCustomerBase.LoginService.ResetPasswordResponse SmileSCustomerBase.LoginService.SmileSLoginServiceSoap.ResetPassword(SmileSCustomerBase.LoginService.ResetPasswordRequest request) {
            return base.Channel.ResetPassword(request);
        }
        
        public bool ResetPassword(string username) {
            SmileSCustomerBase.LoginService.ResetPasswordRequest inValue = new SmileSCustomerBase.LoginService.ResetPasswordRequest();
            inValue.Body = new SmileSCustomerBase.LoginService.ResetPasswordRequestBody();
            inValue.Body.username = username;
            SmileSCustomerBase.LoginService.ResetPasswordResponse retVal = ((SmileSCustomerBase.LoginService.SmileSLoginServiceSoap)(this)).ResetPassword(inValue);
            return retVal.Body.ResetPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmileSCustomerBase.LoginService.ResetPasswordResponse> SmileSCustomerBase.LoginService.SmileSLoginServiceSoap.ResetPasswordAsync(SmileSCustomerBase.LoginService.ResetPasswordRequest request) {
            return base.Channel.ResetPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmileSCustomerBase.LoginService.ResetPasswordResponse> ResetPasswordAsync(string username) {
            SmileSCustomerBase.LoginService.ResetPasswordRequest inValue = new SmileSCustomerBase.LoginService.ResetPasswordRequest();
            inValue.Body = new SmileSCustomerBase.LoginService.ResetPasswordRequestBody();
            inValue.Body.username = username;
            return ((SmileSCustomerBase.LoginService.SmileSLoginServiceSoap)(this)).ResetPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmileSCustomerBase.LoginService.ChangePasswordResponse SmileSCustomerBase.LoginService.SmileSLoginServiceSoap.ChangePassword(SmileSCustomerBase.LoginService.ChangePasswordRequest request) {
            return base.Channel.ChangePassword(request);
        }
        
        public bool ChangePassword(string username, string newPassword) {
            SmileSCustomerBase.LoginService.ChangePasswordRequest inValue = new SmileSCustomerBase.LoginService.ChangePasswordRequest();
            inValue.Body = new SmileSCustomerBase.LoginService.ChangePasswordRequestBody();
            inValue.Body.username = username;
            inValue.Body.newPassword = newPassword;
            SmileSCustomerBase.LoginService.ChangePasswordResponse retVal = ((SmileSCustomerBase.LoginService.SmileSLoginServiceSoap)(this)).ChangePassword(inValue);
            return retVal.Body.ChangePasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmileSCustomerBase.LoginService.ChangePasswordResponse> SmileSCustomerBase.LoginService.SmileSLoginServiceSoap.ChangePasswordAsync(SmileSCustomerBase.LoginService.ChangePasswordRequest request) {
            return base.Channel.ChangePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmileSCustomerBase.LoginService.ChangePasswordResponse> ChangePasswordAsync(string username, string newPassword) {
            SmileSCustomerBase.LoginService.ChangePasswordRequest inValue = new SmileSCustomerBase.LoginService.ChangePasswordRequest();
            inValue.Body = new SmileSCustomerBase.LoginService.ChangePasswordRequestBody();
            inValue.Body.username = username;
            inValue.Body.newPassword = newPassword;
            return ((SmileSCustomerBase.LoginService.SmileSLoginServiceSoap)(this)).ChangePasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmileSCustomerBase.LoginService.ChangePassword_SSSResponse SmileSCustomerBase.LoginService.SmileSLoginServiceSoap.ChangePassword_SSS(SmileSCustomerBase.LoginService.ChangePassword_SSSRequest request) {
            return base.Channel.ChangePassword_SSS(request);
        }
        
        public bool ChangePassword_SSS(string username, string newPassword) {
            SmileSCustomerBase.LoginService.ChangePassword_SSSRequest inValue = new SmileSCustomerBase.LoginService.ChangePassword_SSSRequest();
            inValue.Body = new SmileSCustomerBase.LoginService.ChangePassword_SSSRequestBody();
            inValue.Body.username = username;
            inValue.Body.newPassword = newPassword;
            SmileSCustomerBase.LoginService.ChangePassword_SSSResponse retVal = ((SmileSCustomerBase.LoginService.SmileSLoginServiceSoap)(this)).ChangePassword_SSS(inValue);
            return retVal.Body.ChangePassword_SSSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmileSCustomerBase.LoginService.ChangePassword_SSSResponse> SmileSCustomerBase.LoginService.SmileSLoginServiceSoap.ChangePassword_SSSAsync(SmileSCustomerBase.LoginService.ChangePassword_SSSRequest request) {
            return base.Channel.ChangePassword_SSSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmileSCustomerBase.LoginService.ChangePassword_SSSResponse> ChangePassword_SSSAsync(string username, string newPassword) {
            SmileSCustomerBase.LoginService.ChangePassword_SSSRequest inValue = new SmileSCustomerBase.LoginService.ChangePassword_SSSRequest();
            inValue.Body = new SmileSCustomerBase.LoginService.ChangePassword_SSSRequestBody();
            inValue.Body.username = username;
            inValue.Body.newPassword = newPassword;
            return ((SmileSCustomerBase.LoginService.SmileSLoginServiceSoap)(this)).ChangePassword_SSSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmileSCustomerBase.LoginService.GetMenuListResponse SmileSCustomerBase.LoginService.SmileSLoginServiceSoap.GetMenuList(SmileSCustomerBase.LoginService.GetMenuListRequest request) {
            return base.Channel.GetMenuList(request);
        }
        
        public SmileSCustomerBase.LoginService.MenuList[] GetMenuList(string username, string projectName) {
            SmileSCustomerBase.LoginService.GetMenuListRequest inValue = new SmileSCustomerBase.LoginService.GetMenuListRequest();
            inValue.Body = new SmileSCustomerBase.LoginService.GetMenuListRequestBody();
            inValue.Body.username = username;
            inValue.Body.projectName = projectName;
            SmileSCustomerBase.LoginService.GetMenuListResponse retVal = ((SmileSCustomerBase.LoginService.SmileSLoginServiceSoap)(this)).GetMenuList(inValue);
            return retVal.Body.GetMenuListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmileSCustomerBase.LoginService.GetMenuListResponse> SmileSCustomerBase.LoginService.SmileSLoginServiceSoap.GetMenuListAsync(SmileSCustomerBase.LoginService.GetMenuListRequest request) {
            return base.Channel.GetMenuListAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmileSCustomerBase.LoginService.GetMenuListResponse> GetMenuListAsync(string username, string projectName) {
            SmileSCustomerBase.LoginService.GetMenuListRequest inValue = new SmileSCustomerBase.LoginService.GetMenuListRequest();
            inValue.Body = new SmileSCustomerBase.LoginService.GetMenuListRequestBody();
            inValue.Body.username = username;
            inValue.Body.projectName = projectName;
            return ((SmileSCustomerBase.LoginService.SmileSLoginServiceSoap)(this)).GetMenuListAsync(inValue);
        }
    }
}
