//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileClaimV1.ApplicationService_PH {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usp_CustomerSearch_HeaderInfo_Result", Namespace="http://schemas.datacontract.org/2004/07/SmileSPHService.Model")]
    [System.SerializableAttribute()]
    public partial class usp_CustomerSearch_HeaderInfo_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TotalPagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TotalRecordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TotalPages {
            get {
                return this.TotalPagesField;
            }
            set {
                if ((this.TotalPagesField.Equals(value) != true)) {
                    this.TotalPagesField = value;
                    this.RaisePropertyChanged("TotalPages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TotalRecords {
            get {
                return this.TotalRecordsField;
            }
            set {
                if ((this.TotalRecordsField.Equals(value) != true)) {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usp_CustomerSearch_Select_Result", Namespace="http://schemas.datacontract.org/2004/07/SmileSPHService.Model")]
    [System.SerializableAttribute()]
    public partial class usp_CustomerSearch_Select_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BirthdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CancelDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StartCoverDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationID {
            get {
                return this.ApplicationIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationIDField, value) != true)) {
                    this.ApplicationIDField = value;
                    this.RaisePropertyChanged("ApplicationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationStatus {
            get {
                return this.ApplicationStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationStatusField, value) != true)) {
                    this.ApplicationStatusField = value;
                    this.RaisePropertyChanged("ApplicationStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Birthdate {
            get {
                return this.BirthdateField;
            }
            set {
                if ((this.BirthdateField.Equals(value) != true)) {
                    this.BirthdateField = value;
                    this.RaisePropertyChanged("Birthdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CancelDate {
            get {
                return this.CancelDateField;
            }
            set {
                if ((this.CancelDateField.Equals(value) != true)) {
                    this.CancelDateField = value;
                    this.RaisePropertyChanged("CancelDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartCoverDate {
            get {
                return this.StartCoverDateField;
            }
            set {
                if ((this.StartCoverDateField.Equals(value) != true)) {
                    this.StartCoverDateField = value;
                    this.RaisePropertyChanged("StartCoverDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usp_CustomerDetail_Select_Result", Namespace="http://schemas.datacontract.org/2004/07/SmileSPHService.Model")]
    [System.SerializableAttribute()]
    public partial class usp_CustomerDetail_Select_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AgesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentityNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InsuranceCompanyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StartCoverDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Ages {
            get {
                return this.AgesField;
            }
            set {
                if ((this.AgesField.Equals(value) != true)) {
                    this.AgesField = value;
                    this.RaisePropertyChanged("Ages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationID {
            get {
                return this.ApplicationIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationIDField, value) != true)) {
                    this.ApplicationIDField = value;
                    this.RaisePropertyChanged("ApplicationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentityNumber {
            get {
                return this.IdentityNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentityNumberField, value) != true)) {
                    this.IdentityNumberField = value;
                    this.RaisePropertyChanged("IdentityNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InsuranceCompanyID {
            get {
                return this.InsuranceCompanyIDField;
            }
            set {
                if ((object.ReferenceEquals(this.InsuranceCompanyIDField, value) != true)) {
                    this.InsuranceCompanyIDField = value;
                    this.RaisePropertyChanged("InsuranceCompanyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Passport {
            get {
                return this.PassportField;
            }
            set {
                if ((object.ReferenceEquals(this.PassportField, value) != true)) {
                    this.PassportField = value;
                    this.RaisePropertyChanged("Passport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIDField, value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartCoverDate {
            get {
                return this.StartCoverDateField;
            }
            set {
                if ((this.StartCoverDateField.Equals(value) != true)) {
                    this.StartCoverDateField = value;
                    this.RaisePropertyChanged("StartCoverDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usp_CustomerBenefitDetail_Select_Result", Namespace="http://schemas.datacontract.org/2004/07/SmileSPHService.Model")]
    [System.SerializableAttribute()]
    public partial class usp_CustomerBenefitDetail_Select_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BenefitGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BenefitNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> MaxPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaxQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PricePerUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriceUnitNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuantityUnitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BenefitGroup {
            get {
                return this.BenefitGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.BenefitGroupField, value) != true)) {
                    this.BenefitGroupField = value;
                    this.RaisePropertyChanged("BenefitGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BenefitName {
            get {
                return this.BenefitNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BenefitNameField, value) != true)) {
                    this.BenefitNameField = value;
                    this.RaisePropertyChanged("BenefitName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> MaxPrice {
            get {
                return this.MaxPriceField;
            }
            set {
                if ((this.MaxPriceField.Equals(value) != true)) {
                    this.MaxPriceField = value;
                    this.RaisePropertyChanged("MaxPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaxQuantity {
            get {
                return this.MaxQuantityField;
            }
            set {
                if ((this.MaxQuantityField.Equals(value) != true)) {
                    this.MaxQuantityField = value;
                    this.RaisePropertyChanged("MaxQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> PricePerUnit {
            get {
                return this.PricePerUnitField;
            }
            set {
                if ((this.PricePerUnitField.Equals(value) != true)) {
                    this.PricePerUnitField = value;
                    this.RaisePropertyChanged("PricePerUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriceUnitName {
            get {
                return this.PriceUnitNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceUnitNameField, value) != true)) {
                    this.PriceUnitNameField = value;
                    this.RaisePropertyChanged("PriceUnitName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuantityUnit {
            get {
                return this.QuantityUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.QuantityUnitField, value) != true)) {
                    this.QuantityUnitField = value;
                    this.RaisePropertyChanged("QuantityUnit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usp_BenefitCoverrage_ByBenefitID_Select_Result", Namespace="http://schemas.datacontract.org/2004/07/SmileSPHService.Model")]
    [System.SerializableAttribute()]
    public partial class usp_BenefitCoverrage_ByBenefitID_Select_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BenefitGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BenefitNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> MaxPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaxQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PricePerUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriceUnitNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuantityUnitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BenefitGroup {
            get {
                return this.BenefitGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.BenefitGroupField, value) != true)) {
                    this.BenefitGroupField = value;
                    this.RaisePropertyChanged("BenefitGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BenefitName {
            get {
                return this.BenefitNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BenefitNameField, value) != true)) {
                    this.BenefitNameField = value;
                    this.RaisePropertyChanged("BenefitName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> MaxPrice {
            get {
                return this.MaxPriceField;
            }
            set {
                if ((this.MaxPriceField.Equals(value) != true)) {
                    this.MaxPriceField = value;
                    this.RaisePropertyChanged("MaxPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaxQuantity {
            get {
                return this.MaxQuantityField;
            }
            set {
                if ((this.MaxQuantityField.Equals(value) != true)) {
                    this.MaxQuantityField = value;
                    this.RaisePropertyChanged("MaxQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> PricePerUnit {
            get {
                return this.PricePerUnitField;
            }
            set {
                if ((this.PricePerUnitField.Equals(value) != true)) {
                    this.PricePerUnitField = value;
                    this.RaisePropertyChanged("PricePerUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriceUnitName {
            get {
                return this.PriceUnitNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceUnitNameField, value) != true)) {
                    this.PriceUnitNameField = value;
                    this.RaisePropertyChanged("PriceUnitName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuantityUnit {
            get {
                return this.QuantityUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.QuantityUnitField, value) != true)) {
                    this.QuantityUnitField = value;
                    this.RaisePropertyChanged("QuantityUnit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ApplicationService_PH.IApplicationService")]
    public interface IApplicationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicationService/CustomerSearchHeaderInfo", ReplyAction="http://tempuri.org/IApplicationService/CustomerSearchHeaderInfoResponse")]
        SmileClaimV1.ApplicationService_PH.usp_CustomerSearch_HeaderInfo_Result CustomerSearchHeaderInfo(int pageSize, string criteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicationService/CustomerSearchHeaderInfo", ReplyAction="http://tempuri.org/IApplicationService/CustomerSearchHeaderInfoResponse")]
        System.Threading.Tasks.Task<SmileClaimV1.ApplicationService_PH.usp_CustomerSearch_HeaderInfo_Result> CustomerSearchHeaderInfoAsync(int pageSize, string criteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicationService/CustomerSearch", ReplyAction="http://tempuri.org/IApplicationService/CustomerSearchResponse")]
        SmileClaimV1.ApplicationService_PH.usp_CustomerSearch_Select_Result[] CustomerSearch(string criteria, int rowsPerPage, int pageNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicationService/CustomerSearch", ReplyAction="http://tempuri.org/IApplicationService/CustomerSearchResponse")]
        System.Threading.Tasks.Task<SmileClaimV1.ApplicationService_PH.usp_CustomerSearch_Select_Result[]> CustomerSearchAsync(string criteria, int rowsPerPage, int pageNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicationService/GetCustomerDetail", ReplyAction="http://tempuri.org/IApplicationService/GetCustomerDetailResponse")]
        SmileClaimV1.ApplicationService_PH.usp_CustomerDetail_Select_Result GetCustomerDetail(string _applicationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicationService/GetCustomerDetail", ReplyAction="http://tempuri.org/IApplicationService/GetCustomerDetailResponse")]
        System.Threading.Tasks.Task<SmileClaimV1.ApplicationService_PH.usp_CustomerDetail_Select_Result> GetCustomerDetailAsync(string _applicationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicationService/GetCustomerBenefitDetail", ReplyAction="http://tempuri.org/IApplicationService/GetCustomerBenefitDetailResponse")]
        SmileClaimV1.ApplicationService_PH.usp_CustomerBenefitDetail_Select_Result[] GetCustomerBenefitDetail(string _applicationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicationService/GetCustomerBenefitDetail", ReplyAction="http://tempuri.org/IApplicationService/GetCustomerBenefitDetailResponse")]
        System.Threading.Tasks.Task<SmileClaimV1.ApplicationService_PH.usp_CustomerBenefitDetail_Select_Result[]> GetCustomerBenefitDetailAsync(string _applicationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicationService/GetCoverageByBenefitID", ReplyAction="http://tempuri.org/IApplicationService/GetCoverageByBenefitIDResponse")]
        SmileClaimV1.ApplicationService_PH.usp_BenefitCoverrage_ByBenefitID_Select_Result[] GetCoverageByBenefitID(string _applicationID, string _benefitID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicationService/GetCoverageByBenefitID", ReplyAction="http://tempuri.org/IApplicationService/GetCoverageByBenefitIDResponse")]
        System.Threading.Tasks.Task<SmileClaimV1.ApplicationService_PH.usp_BenefitCoverrage_ByBenefitID_Select_Result[]> GetCoverageByBenefitIDAsync(string _applicationID, string _benefitID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IApplicationServiceChannel : SmileClaimV1.ApplicationService_PH.IApplicationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApplicationServiceClient : System.ServiceModel.ClientBase<SmileClaimV1.ApplicationService_PH.IApplicationService>, SmileClaimV1.ApplicationService_PH.IApplicationService {
        
        public ApplicationServiceClient() {
        }
        
        public ApplicationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApplicationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SmileClaimV1.ApplicationService_PH.usp_CustomerSearch_HeaderInfo_Result CustomerSearchHeaderInfo(int pageSize, string criteria) {
            return base.Channel.CustomerSearchHeaderInfo(pageSize, criteria);
        }
        
        public System.Threading.Tasks.Task<SmileClaimV1.ApplicationService_PH.usp_CustomerSearch_HeaderInfo_Result> CustomerSearchHeaderInfoAsync(int pageSize, string criteria) {
            return base.Channel.CustomerSearchHeaderInfoAsync(pageSize, criteria);
        }
        
        public SmileClaimV1.ApplicationService_PH.usp_CustomerSearch_Select_Result[] CustomerSearch(string criteria, int rowsPerPage, int pageNumber) {
            return base.Channel.CustomerSearch(criteria, rowsPerPage, pageNumber);
        }
        
        public System.Threading.Tasks.Task<SmileClaimV1.ApplicationService_PH.usp_CustomerSearch_Select_Result[]> CustomerSearchAsync(string criteria, int rowsPerPage, int pageNumber) {
            return base.Channel.CustomerSearchAsync(criteria, rowsPerPage, pageNumber);
        }
        
        public SmileClaimV1.ApplicationService_PH.usp_CustomerDetail_Select_Result GetCustomerDetail(string _applicationID) {
            return base.Channel.GetCustomerDetail(_applicationID);
        }
        
        public System.Threading.Tasks.Task<SmileClaimV1.ApplicationService_PH.usp_CustomerDetail_Select_Result> GetCustomerDetailAsync(string _applicationID) {
            return base.Channel.GetCustomerDetailAsync(_applicationID);
        }
        
        public SmileClaimV1.ApplicationService_PH.usp_CustomerBenefitDetail_Select_Result[] GetCustomerBenefitDetail(string _applicationID) {
            return base.Channel.GetCustomerBenefitDetail(_applicationID);
        }
        
        public System.Threading.Tasks.Task<SmileClaimV1.ApplicationService_PH.usp_CustomerBenefitDetail_Select_Result[]> GetCustomerBenefitDetailAsync(string _applicationID) {
            return base.Channel.GetCustomerBenefitDetailAsync(_applicationID);
        }
        
        public SmileClaimV1.ApplicationService_PH.usp_BenefitCoverrage_ByBenefitID_Select_Result[] GetCoverageByBenefitID(string _applicationID, string _benefitID) {
            return base.Channel.GetCoverageByBenefitID(_applicationID, _benefitID);
        }
        
        public System.Threading.Tasks.Task<SmileClaimV1.ApplicationService_PH.usp_BenefitCoverrage_ByBenefitID_Select_Result[]> GetCoverageByBenefitIDAsync(string _applicationID, string _benefitID) {
            return base.Channel.GetCoverageByBenefitIDAsync(_applicationID, _benefitID);
        }
    }
}
