//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSClaimPayBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimPayBack
    {
        public int ClaimPayBackId { get; set; }
        public string ClaimPayBackCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> ClaimPayBackStatusId { get; set; }
        public Nullable<int> ClaimGroupTypeId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> ClaimPayBackTransferId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> GroupId { get; set; }
    }
}
