//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSClaimPayBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimPayBackXClaim
    {
        public int ClaimPayBackXClaimId { get; set; }
        public Nullable<int> ClaimPayBackDetailId { get; set; }
        public string ClaimCode { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string HospitalCode { get; set; }
        public string HospitalName { get; set; }
        public string ClaimAdmitTypeCode { get; set; }
        public string ClaimAdmitType { get; set; }
        public string ChiefComplainCode { get; set; }
        public string ChiefComplain { get; set; }
        public string ICD10Code { get; set; }
        public string ICD10 { get; set; }
        public Nullable<decimal> ClaimPay { get; set; }
        public Nullable<decimal> ClaimTransfer { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CustomerName { get; set; }
        public Nullable<System.DateTime> AdmitDate { get; set; }
        public string SchoolName { get; set; }
    }
}
