//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSCommissionModelDesigner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_BRANCH
    {
        public int Id { get; set; }
        public Nullable<int> Period_Id { get; set; }
        public string MainKey { get; set; }
        public string Branch { get; set; }
        public string App_Branch_All { get; set; }
        public string Lapse_Branch_All { get; set; }
        public string Balance_Branch_All { get; set; }
        public string App_Branch_24 { get; set; }
        public string Lapse_Branch_24 { get; set; }
        public string Balance_Branch_24 { get; set; }
        public string App_Branch_25 { get; set; }
        public string Lapse_Branch_25 { get; set; }
        public string Balance_Branch_25 { get; set; }
        public string Point_UnderWrite_Area_Overdue_All { get; set; }
        public string Lapse_Disability_Branch { get; set; }
        public string Count_FM_Branch { get; set; }
        public string NewApp_FM_In_Branch { get; set; }
        public string Balance_Branch_Current { get; set; }
        public string Balance_Branch_Lastmonth { get; set; }
        public string Growth_Branch { get; set; }
        public string Lapse_Real_Branch { get; set; }
        public string Lapse_Dead_Branch { get; set; }
        public string Lapse_Complete_The_Contract_Branch { get; set; }
        public string Lapse_LG_Branch_Current { get; set; }
        public string Percentage_Lapse_Branch { get; set; }
        public string Percentage_Best_Lapse_Branch_LastMonth { get; set; }
        public string Grade_LG_Branch { get; set; }
        public string Premium_Branch_12Month { get; set; }
        public string Claim_Branch_12Month { get; set; }
        public string Loss_Claim_Branch_Current { get; set; }
        public string Best_Loss_Claim_Branch_LastMonth { get; set; }
        public string Grade_LRG_Branch { get; set; }
        public string Count_Premium_System_Branch { get; set; }
        public string Percentage_Premium_System_Branch { get; set; }
        public string Grade_PSG_Branch { get; set; }
        public string Count_Premium_Operation_Branch { get; set; }
        public string Percentage_Premium_Operation_Branch { get; set; }
        public string Grade_POG_Branch { get; set; }
        public string UnderWrite_Branch { get; set; }
        public string Percentege_UW_Branch { get; set; }
        public string Grade_UWG_Branch { get; set; }
        public string NewApp_FM_In_Branch_Week1 { get; set; }
        public string NewApp_FM_In_Branch_Week2 { get; set; }
        public string NewApp_FM_In_Branch_Week3 { get; set; }
        public string NewApp_FM_In_Branch_Week4 { get; set; }
        public string NewApp_FM_In_Branch_Week5 { get; set; }
        public string Point_UWG_Area { get; set; }
        public string Percentage_Best_Lapse_Branch_NextMonth { get; set; }
        public string Best_Loss_Claim_Branch_NextMonth { get; set; }
    }
}
