//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSCommissionModelDesigner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_ClaimOnline
    {
        public int Id { get; set; }
        public Nullable<int> Period_Id { get; set; }
        public Nullable<double> RewardHistoryId { get; set; }
        public Nullable<double> RewardId { get; set; }
        public Nullable<double> ClaimOnLineId { get; set; }
        public string ClaimOnLineCode { get; set; }
        public string ClaimHeaderCode { get; set; }
        public string ClaimCode { get; set; }
        public Nullable<double> Pay { get; set; }
        public Nullable<double> UnPay { get; set; }
        public Nullable<double> ProductTypeId { get; set; }
        public string ProductType { get; set; }
        public string Detail { get; set; }
        public string Zone { get; set; }
        public string Branch { get; set; }
        public string ServiceByEmpCode { get; set; }
        public string ServiceByEmpName { get; set; }
        public Nullable<System.DateTime> TransferDateStart { get; set; }
        public Nullable<double> TransferDateStart_D { get; set; }
        public Nullable<double> TransferDateStart_M { get; set; }
        public Nullable<double> TransferDateStart_Y { get; set; }
        public Nullable<System.DateTime> ReturnDateFinal { get; set; }
        public Nullable<double> ReturnDateFinal_D { get; set; }
        public Nullable<double> ReturnDateFinal_M { get; set; }
        public Nullable<double> ReturnDateFinal_Y { get; set; }
        public Nullable<double> OperateDays { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<double> CreatedDate_D { get; set; }
        public Nullable<double> CreatedDate_M { get; set; }
        public Nullable<double> CreatedDate_Y { get; set; }
    }
}
