//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSCommissionModelDesigner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_Collect_Branch
    {
        public int Id { get; set; }
        public Nullable<int> Period_Id { get; set; }
        public Nullable<double> ReferenceTypeId { get; set; }
        public string ReferenceType { get; set; }
        public string ReferenceCode { get; set; }
        public string ReferenceDetail { get; set; }
        public string ProductGroupCode { get; set; }
        public string ProductGroup { get; set; }
        public Nullable<double> CountReceive { get; set; }
        public Nullable<double> CountUnReceive { get; set; }
        public Nullable<double> CountAll { get; set; }
    }
}
