//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSCommissionModelDesigner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_NewAppMP
    {
        public int Id { get; set; }
        public Nullable<int> Period_Id { get; set; }
        public string MotorApplication_Code { get; set; }
        public Nullable<double> MotorApplicationStatus_ID { get; set; }
        public string MotorApplicationStatusDetail { get; set; }
        public Nullable<double> MotorApplicationContractType_ID { get; set; }
        public string MotorApplicationContractTypeDetail { get; set; }
        public Nullable<System.DateTime> StartCover { get; set; }
        public Nullable<double> StartCover_D { get; set; }
        public Nullable<double> StartCover_M { get; set; }
        public Nullable<double> StartCover_Y { get; set; }
        public Nullable<System.DateTime> EndCover { get; set; }
        public Nullable<double> EndCover_D { get; set; }
        public Nullable<double> EndCover_M { get; set; }
        public Nullable<double> EndCover_Y { get; set; }
        public Nullable<double> ProductType_ID { get; set; }
        public string ProductTypeDetail { get; set; }
        public Nullable<double> Product_ID { get; set; }
        public string ProductDetail { get; set; }
        public Nullable<double> PremiumPerMonth { get; set; }
        public Nullable<double> PremiumPerYear { get; set; }
        public Nullable<double> PeriodType_ID { get; set; }
        public string PeriodTypeDetail { get; set; }
        public string CustName { get; set; }
        public string PayerName { get; set; }
        public string PayerWorkAddress_FullDetail { get; set; }
        public string PayerWorkAddress_Province_ID { get; set; }
        public string PayerWorkAddress_ProvinceDetail { get; set; }
        public string PayerWorkAddress_District_ID { get; set; }
        public string PayerWorkAddress_DistrictDetail { get; set; }
        public string PayerWorkAddress_SubDistrict_ID { get; set; }
        public string PayerWorkAddress_SubDistrictDetail { get; set; }
        public Nullable<double> PayerBranch_ID { get; set; }
        public string PayerBranchDetail { get; set; }
        public Nullable<double> PayerStudyArea_id { get; set; }
        public string PayerStudyArea { get; set; }
        public string Sale1_Employee_Code { get; set; }
        public Nullable<double> Sale1_Branch_ID { get; set; }
        public string Sale1_BranchDetail { get; set; }
        public string VehicleRegistrationDetail { get; set; }
        public string VehicleRegistrationNumber { get; set; }
        public string VehicleRegistrationProvince { get; set; }
        public string CreateBy_Employee_Code { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<double> CreatedDate_D { get; set; }
        public Nullable<double> CreatedDate_M { get; set; }
        public Nullable<double> CreatedDate_Y { get; set; }
        public string ApproveBy_Employee_Code { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public Nullable<double> ApproveDate_D { get; set; }
        public Nullable<double> ApproveDate_M { get; set; }
        public Nullable<double> ApproveDate_Y { get; set; }
    }
}
