//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSCommission.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_MSN
    {
        public int Id { get; set; }
        public Nullable<int> Period_Id { get; set; }
        public string MainKey { get; set; }
        public string HCM_ID { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeStatus { get; set; }
        public string BranchCode { get; set; }
        public string Branch { get; set; }
        public string NewApp_PH_Team_MSN { get; set; }
        public string Point_NewApp_PH_Team_MSN { get; set; }
        public string Position_Level { get; set; }
        public string Position_Abbr { get; set; }
        public string Position_Abbr_SSS { get; set; }
        public string NewApp_MP_Team_MSN { get; set; }
        public string Commission_NewApp_MP_Team_MSN { get; set; }
        public string NewApp_HP_Team_MSN { get; set; }
        public string Commission_NewApp_HP_Team_MSN { get; set; }
        public string Commission_Team_MSN_All { get; set; }
        public string Point_Team_MSN_All { get; set; }
    }
}
