//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSCommission.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TEAM_MS
    {
        public int Id { get; set; }
        public Nullable<int> Period_Id { get; set; }
        public string MainKey { get; set; }
        public string HCM_ID { get; set; }
        public string Employee_Name { get; set; }
        public string Employee_Status { get; set; }
        public string Leave_Type_Name { get; set; }
        public string Branch_Code { get; set; }
        public string Branch { get; set; }
        public string Team_Code { get; set; }
        public string Team { get; set; }
        public string Position_Level { get; set; }
        public string Position_Abbr { get; set; }
        public string Position_Abbr_SSS { get; set; }
        public string Commission_Target_Team { get; set; }
        public string NewApp_Team_PH902 { get; set; }
        public string NewApp_Team_PH902_Point { get; set; }
        public string NewApp_Team_PH502 { get; set; }
        public string NewApp_Team_PH502_Point { get; set; }
        public string NewApp_Team_PH503 { get; set; }
        public string NewApp_Team_PH503_Point { get; set; }
        public string NewApp_Team_PHs150 { get; set; }
        public string NewApp_Team_PHs150_Point { get; set; }
        public string NewApp_Team_PH601 { get; set; }
        public string NewApp_Team_PH601_Point { get; set; }
        public string NewApp_Team_PH621 { get; set; }
        public string NewApp_Team_PH621_Point { get; set; }
        public string NewApp_Team_PH_PointAll { get; set; }
        public string NewApp_Team_MP { get; set; }
        public string NewApp_Team_MP_Point { get; set; }
        public string NewApp_Team_HP { get; set; }
        public string UWG_Team { get; set; }
        public string Adjust_Team_PHs150_Point_Credit { get; set; }
        public string Lapse_Adjust_Team_PH601 { get; set; }
        public string Target_Team_Grade { get; set; }
        public string NewApp_Team_PH { get; set; }
        public string UnderWrite { get; set; }
        public string Adjust_Team_PH902_Point { get; set; }
        public string NewApp_Team { get; set; }
        public string Percentage_Adjust_Point_Credit { get; set; }
        public string Adjust_Team_PH502_Point_Credit { get; set; }
        public string Lapse_Adjust_Team_PH902 { get; set; }
        public string NewApp_Team_HP_Point { get; set; }
        public string UWG_Team_Point { get; set; }
        public string Adjust_Team_PH902_Point_Credit { get; set; }
        public string Lapse_Adjust_Team_PH502 { get; set; }
        public string Adjust_Team_PH502_Point { get; set; }
        public string Lapse_Adjust_Team_PH503 { get; set; }
        public string Adjust_Team_PH503_Point { get; set; }
        public string Adjust_Team_PH503_Point_Credit { get; set; }
        public string Lapse_Adjust_Team_PHs150 { get; set; }
        public string Adjust_Team_PHs150_Point { get; set; }
        public string Adjust_Team_PH601_Point { get; set; }
        public string Adjust_Team_PH601_Point_Credit { get; set; }
        public string Adjust_Team_PH621_Point_Credit { get; set; }
        public string Adjust_Team_PH621_Point { get; set; }
        public string Lapse_Adjust_Team_PH621 { get; set; }
        public string Lapse_Adjust_Team_PL100000 { get; set; }
        public string Adjust_Team_PL100000_Point { get; set; }
        public string Lapse_Adjust_Team_PL200000 { get; set; }
        public string Lapse_Adjust_Team_PL300000 { get; set; }
        public string Lapse_Adjust_Team_PL400000 { get; set; }
        public string Lapse_Adjust_Team_PL500000 { get; set; }
        public string Adjust_Team_PL200000_Point { get; set; }
        public string Adjust_Team_PL300000_Point { get; set; }
        public string Adjust_Team_PL400000_Point { get; set; }
        public string Adjust_Team_PL500000_Point { get; set; }
        public string Lapse_Adjust_Team_MP_Old { get; set; }
        public string Adjust_Team_MP_Old_Point { get; set; }
        public string Lapse_Adjust_Team_MP_New { get; set; }
        public string Adjust_Team_MP_New_Point { get; set; }
        public string Lapse_Adjust_Team_HP { get; set; }
        public string Adjust_Team_HP_Point { get; set; }
        public string Target_Team_Week1_Point { get; set; }
        public string Target_Team_Week2_Point { get; set; }
        public string Target_Team_Week3_Point { get; set; }
        public string Target_Team_Week4_Point { get; set; }
        public string Target_Team_Week5_Point { get; set; }
        public string NewApp_Team_Week1 { get; set; }
        public string NewApp_Team_Week2 { get; set; }
        public string NewApp_Team_Week3 { get; set; }
        public string NewApp_Team_Week4 { get; set; }
        public string NewApp_Team_Week5 { get; set; }
        public string Commission_Team_All { get; set; }
        public string Point_Team_All { get; set; }
        public string Average_Team_Week1 { get; set; }
        public string Count_Personal_Team { get; set; }
        public string Average_Team_Week2 { get; set; }
        public string Average_Team_Week3 { get; set; }
        public string Average_Team_Week4 { get; set; }
        public string Average_Team_Week5 { get; set; }
    }
}
