//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSCommission.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CommissionCalculateEntities : DbContext
    {
        public CommissionCalculateEntities()
            : base("name=CommissionCalculateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_Kead_Personal> C_Kead_Personal { get; set; }
        public virtual DbSet<C_KehTest> C_KehTest { get; set; }
        public virtual DbSet<CommissionPeriod> CommissionPeriod { get; set; }
        public virtual DbSet<CommissionPeriodStatus> CommissionPeriodStatus { get; set; }
        public virtual DbSet<D_Area> D_Area { get; set; }
        public virtual DbSet<D_Area_Calculation_LastMonth> D_Area_Calculation_LastMonth { get; set; }
        public virtual DbSet<D_Branch> D_Branch { get; set; }
        public virtual DbSet<D_Branch_Calculation_LastMonth> D_Branch_Calculation_LastMonth { get; set; }
        public virtual DbSet<D_ClaimHouse> D_ClaimHouse { get; set; }
        public virtual DbSet<D_ClaimLRG_PH_Area_Current> D_ClaimLRG_PH_Area_Current { get; set; }
        public virtual DbSet<D_ClaimLRG_PH_Branch_Current> D_ClaimLRG_PH_Branch_Current { get; set; }
        public virtual DbSet<D_ClaimLRG_PH_Personal_Current> D_ClaimLRG_PH_Personal_Current { get; set; }
        public virtual DbSet<D_ClaimMotor> D_ClaimMotor { get; set; }
        public virtual DbSet<D_ClaimNonMotor_OnLine> D_ClaimNonMotor_OnLine { get; set; }
        public virtual DbSet<D_Data_MP_Area> D_Data_MP_Area { get; set; }
        public virtual DbSet<D_Data_MP_Branch> D_Data_MP_Branch { get; set; }
        public virtual DbSet<D_Data_MP_Personal> D_Data_MP_Personal { get; set; }
        public virtual DbSet<D_Data_PH_Area_0499> D_Data_PH_Area_0499 { get; set; }
        public virtual DbSet<D_Data_PH_Area_No0499> D_Data_PH_Area_No0499 { get; set; }
        public virtual DbSet<D_Data_PH_Branch_0499> D_Data_PH_Branch_0499 { get; set; }
        public virtual DbSet<D_Data_PH_Branch_No0499> D_Data_PH_Branch_No0499 { get; set; }
        public virtual DbSet<D_Data_PH_Personal> D_Data_PH_Personal { get; set; }
        public virtual DbSet<D_Employee> D_Employee { get; set; }
        public virtual DbSet<D_Employee_CB_PB> D_Employee_CB_PB { get; set; }
        public virtual DbSet<D_Employee_DA> D_Employee_DA { get; set; }
        public virtual DbSet<D_Employee_DB> D_Employee_DB { get; set; }
        public virtual DbSet<D_Employee_DM> D_Employee_DM { get; set; }
        public virtual DbSet<D_Employee_DS> D_Employee_DS { get; set; }
        public virtual DbSet<D_Employee_HCM> D_Employee_HCM { get; set; }
        public virtual DbSet<D_Employee_HO_AHO> D_Employee_HO_AHO { get; set; }
        public virtual DbSet<D_Employee_MM> D_Employee_MM { get; set; }
        public virtual DbSet<D_Employee_MMR> D_Employee_MMR { get; set; }
        public virtual DbSet<D_Employee_MS> D_Employee_MS { get; set; }
        public virtual DbSet<D_Employee_MSR> D_Employee_MSR { get; set; }
        public virtual DbSet<D_Employee_Zebra> D_Employee_Zebra { get; set; }
        public virtual DbSet<D_Lapse> D_Lapse { get; set; }
        public virtual DbSet<D_LapseMP> D_LapseMP { get; set; }
        public virtual DbSet<D_LapseMPV1> D_LapseMPV1 { get; set; }
        public virtual DbSet<D_LapseMPV2> D_LapseMPV2 { get; set; }
        public virtual DbSet<D_LapseV1> D_LapseV1 { get; set; }
        public virtual DbSet<D_LapseV2> D_LapseV2 { get; set; }
        public virtual DbSet<D_LapseV3> D_LapseV3 { get; set; }
        public virtual DbSet<D_NewApp_Goft> D_NewApp_Goft { get; set; }
        public virtual DbSet<D_NewApp_PA200> D_NewApp_PA200 { get; set; }
        public virtual DbSet<D_NewApp_PAGroup> D_NewApp_PAGroup { get; set; }
        public virtual DbSet<D_NewApp_SmilePA> D_NewApp_SmilePA { get; set; }
        public virtual DbSet<D_NewApp_TA_Domestic> D_NewApp_TA_Domestic { get; set; }
        public virtual DbSet<D_NewApp_TA_Inter> D_NewApp_TA_Inter { get; set; }
        public virtual DbSet<D_NewAppCompulsory> D_NewAppCompulsory { get; set; }
        public virtual DbSet<D_NewAppHP> D_NewAppHP { get; set; }
        public virtual DbSet<D_NewAppHQ> D_NewAppHQ { get; set; }
        public virtual DbSet<D_NewAppMP> D_NewAppMP { get; set; }
        public virtual DbSet<D_NewAppMQ> D_NewAppMQ { get; set; }
        public virtual DbSet<D_NewAppPA30> D_NewAppPA30 { get; set; }
        public virtual DbSet<D_NewAppPACommunity> D_NewAppPACommunity { get; set; }
        public virtual DbSet<D_NewAppPH> D_NewAppPH { get; set; }
        public virtual DbSet<D_NewAppPL> D_NewAppPL { get; set; }
        public virtual DbSet<D_OperatingCapital> D_OperatingCapital { get; set; }
        public virtual DbSet<D_PA_Premium> D_PA_Premium { get; set; }
        public virtual DbSet<D_Personal_Calculation_LastMonth> D_Personal_Calculation_LastMonth { get; set; }
        public virtual DbSet<D_Recover> D_Recover { get; set; }
        public virtual DbSet<D_ReportBeforeCover> D_ReportBeforeCover { get; set; }
        public virtual DbSet<D_Team> D_Team { get; set; }
        public virtual DbSet<D_UnApprovedUnderwrite> D_UnApprovedUnderwrite { get; set; }
        public virtual DbSet<D_UnApprovedUnderwrite_PriorMonth> D_UnApprovedUnderwrite_PriorMonth { get; set; }
        public virtual DbSet<D_UnderwriteCondition> D_UnderwriteCondition { get; set; }
        public virtual DbSet<D_UnderwriteOverDue> D_UnderwriteOverDue { get; set; }
        public virtual DbSet<D_WeeklySaleTarget> D_WeeklySaleTarget { get; set; }
        public virtual DbSet<D_WeeklySaleTargetBranchPB_CB> D_WeeklySaleTargetBranchPB_CB { get; set; }
        public virtual DbSet<D_Zebra> D_Zebra { get; set; }
        public virtual DbSet<D_Zebra_Calculation_LastMonth> D_Zebra_Calculation_LastMonth { get; set; }
        public virtual DbSet<DatasourceImportedEditCause> DatasourceImportedEditCause { get; set; }
        public virtual DbSet<DatasourceImportedLog> DatasourceImportedLog { get; set; }
        public virtual DbSet<DatasourceImportedStatus> DatasourceImportedStatus { get; set; }
        public virtual DbSet<DatasourceImportedType> DatasourceImportedType { get; set; }
        public virtual DbSet<DataSourceMaster> DataSourceMaster { get; set; }
        public virtual DbSet<DesignerModel> DesignerModel { get; set; }
        public virtual DbSet<DesignerModelConfig> DesignerModelConfig { get; set; }
        public virtual DbSet<DesignerModelDatasource> DesignerModelDatasource { get; set; }
        public virtual DbSet<DesignerParameter> DesignerParameter { get; set; }
        public virtual DbSet<Model> Model { get; set; }
        public virtual DbSet<ModelCalculationIndex> ModelCalculationIndex { get; set; }
        public virtual DbSet<ModelConfig> ModelConfig { get; set; }
        public virtual DbSet<ModelDatasource> ModelDatasource { get; set; }
        public virtual DbSet<ModelParameter> ModelParameter { get; set; }
        public virtual DbSet<ModelParameterDescription> ModelParameterDescription { get; set; }
        public virtual DbSet<ParamValue> ParamValue { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ValidApp_Id> ValidApp_Id { get; set; }
        public virtual DbSet<ValidArea> ValidArea { get; set; }
        public virtual DbSet<ValidBranch> ValidBranch { get; set; }
        public virtual DbSet<ValidClaim_Id> ValidClaim_Id { get; set; }
        public virtual DbSet<ValidDistrict> ValidDistrict { get; set; }
        public virtual DbSet<ValidEmployeeSS> ValidEmployeeSS { get; set; }
        public virtual DbSet<ValidHC> ValidHC { get; set; }
        public virtual DbSet<ValidProvince> ValidProvince { get; set; }
        public virtual DbSet<ValidTeam> ValidTeam { get; set; }
        public virtual DbSet<ValidZebra> ValidZebra { get; set; }
        public virtual DbSet<D_Premium_System_MP_Area> D_Premium_System_MP_Area { get; set; }
        public virtual DbSet<D_Premium_System_MP_Branch> D_Premium_System_MP_Branch { get; set; }
        public virtual DbSet<D_Premium_System_MP_Personal> D_Premium_System_MP_Personal { get; set; }
        public virtual DbSet<D_Premium_System_PH_Area> D_Premium_System_PH_Area { get; set; }
        public virtual DbSet<D_Premium_System_PH_Branch> D_Premium_System_PH_Branch { get; set; }
        public virtual DbSet<D_Premium_System_PH_Personal> D_Premium_System_PH_Personal { get; set; }
    
        public virtual ObjectResult<usp_CommissionPeriod_Datatable_Result> usp_CommissionPeriod_Datatable(string criteria, Nullable<int> pageStart, Nullable<int> pageSize, string sortField, string orderType)
        {
            var criteriaParameter = criteria != null ?
                new ObjectParameter("criteria", criteria) :
                new ObjectParameter("criteria", typeof(string));
    
            var pageStartParameter = pageStart.HasValue ?
                new ObjectParameter("pageStart", pageStart) :
                new ObjectParameter("pageStart", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var sortFieldParameter = sortField != null ?
                new ObjectParameter("sortField", sortField) :
                new ObjectParameter("sortField", typeof(string));
    
            var orderTypeParameter = orderType != null ?
                new ObjectParameter("orderType", orderType) :
                new ObjectParameter("orderType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CommissionPeriod_Datatable_Result>("usp_CommissionPeriod_Datatable", criteriaParameter, pageStartParameter, pageSizeParameter, sortFieldParameter, orderTypeParameter);
        }
    
        public virtual ObjectResult<usp_CommissionPeriod_Insert_Result> usp_CommissionPeriod_Insert(Nullable<System.DateTime> payPeriod, string description, string createdBy)
        {
            var payPeriodParameter = payPeriod.HasValue ?
                new ObjectParameter("PayPeriod", payPeriod) :
                new ObjectParameter("PayPeriod", typeof(System.DateTime));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CommissionPeriod_Insert_Result>("usp_CommissionPeriod_Insert", payPeriodParameter, descriptionParameter, createdByParameter);
        }
    
        public virtual ObjectResult<usp_CommissionPeriod_Select_Result> usp_CommissionPeriod_Select(Nullable<int> payPeriodId, Nullable<int> commissionPeriodStatusId, Nullable<int> indexStart, Nullable<int> pageSize, string sortField, string orderType, string searchDetail)
        {
            var payPeriodIdParameter = payPeriodId.HasValue ?
                new ObjectParameter("payPeriodId", payPeriodId) :
                new ObjectParameter("payPeriodId", typeof(int));
    
            var commissionPeriodStatusIdParameter = commissionPeriodStatusId.HasValue ?
                new ObjectParameter("commissionPeriodStatusId", commissionPeriodStatusId) :
                new ObjectParameter("commissionPeriodStatusId", typeof(int));
    
            var indexStartParameter = indexStart.HasValue ?
                new ObjectParameter("indexStart", indexStart) :
                new ObjectParameter("indexStart", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var sortFieldParameter = sortField != null ?
                new ObjectParameter("sortField", sortField) :
                new ObjectParameter("sortField", typeof(string));
    
            var orderTypeParameter = orderType != null ?
                new ObjectParameter("orderType", orderType) :
                new ObjectParameter("orderType", typeof(string));
    
            var searchDetailParameter = searchDetail != null ?
                new ObjectParameter("searchDetail", searchDetail) :
                new ObjectParameter("searchDetail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CommissionPeriod_Select_Result>("usp_CommissionPeriod_Select", payPeriodIdParameter, commissionPeriodStatusIdParameter, indexStartParameter, pageSizeParameter, sortFieldParameter, orderTypeParameter, searchDetailParameter);
        }
    
        public virtual ObjectResult<usp_CommissionPeriod_Update_Result> usp_CommissionPeriod_Update(Nullable<int> payPeriodId, string description, string createdBy)
        {
            var payPeriodIdParameter = payPeriodId.HasValue ?
                new ObjectParameter("payPeriodId", payPeriodId) :
                new ObjectParameter("payPeriodId", typeof(int));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("createdBy", createdBy) :
                new ObjectParameter("createdBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CommissionPeriod_Update_Result>("usp_CommissionPeriod_Update", payPeriodIdParameter, descriptionParameter, createdByParameter);
        }
    
        public virtual ObjectResult<usp_CloneDataSource_Result> usp_CloneDataSource(Nullable<int> fromPeriodId, Nullable<int> toPeriodId, string createdBy)
        {
            var fromPeriodIdParameter = fromPeriodId.HasValue ?
                new ObjectParameter("fromPeriodId", fromPeriodId) :
                new ObjectParameter("fromPeriodId", typeof(int));
    
            var toPeriodIdParameter = toPeriodId.HasValue ?
                new ObjectParameter("toPeriodId", toPeriodId) :
                new ObjectParameter("toPeriodId", typeof(int));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("createdBy", createdBy) :
                new ObjectParameter("createdBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CloneDataSource_Result>("usp_CloneDataSource", fromPeriodIdParameter, toPeriodIdParameter, createdByParameter);
        }
    
        public virtual ObjectResult<usp_CommissionPeriodSearch_Select_Result> usp_CommissionPeriodSearch_Select(Nullable<System.DateTime> payPeriod, Nullable<bool> isWaitProcess, Nullable<bool> isSentPayroll, Nullable<bool> isSucess, Nullable<bool> isCancel, Nullable<int> indexStart, Nullable<int> pageSize, string sortField, string orderType, string searchDetail)
        {
            var payPeriodParameter = payPeriod.HasValue ?
                new ObjectParameter("payPeriod", payPeriod) :
                new ObjectParameter("payPeriod", typeof(System.DateTime));
    
            var isWaitProcessParameter = isWaitProcess.HasValue ?
                new ObjectParameter("isWaitProcess", isWaitProcess) :
                new ObjectParameter("isWaitProcess", typeof(bool));
    
            var isSentPayrollParameter = isSentPayroll.HasValue ?
                new ObjectParameter("isSentPayroll", isSentPayroll) :
                new ObjectParameter("isSentPayroll", typeof(bool));
    
            var isSucessParameter = isSucess.HasValue ?
                new ObjectParameter("isSucess", isSucess) :
                new ObjectParameter("isSucess", typeof(bool));
    
            var isCancelParameter = isCancel.HasValue ?
                new ObjectParameter("isCancel", isCancel) :
                new ObjectParameter("isCancel", typeof(bool));
    
            var indexStartParameter = indexStart.HasValue ?
                new ObjectParameter("IndexStart", indexStart) :
                new ObjectParameter("IndexStart", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortFieldParameter = sortField != null ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(string));
    
            var orderTypeParameter = orderType != null ?
                new ObjectParameter("OrderType", orderType) :
                new ObjectParameter("OrderType", typeof(string));
    
            var searchDetailParameter = searchDetail != null ?
                new ObjectParameter("SearchDetail", searchDetail) :
                new ObjectParameter("SearchDetail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CommissionPeriodSearch_Select_Result>("usp_CommissionPeriodSearch_Select", payPeriodParameter, isWaitProcessParameter, isSentPayrollParameter, isSucessParameter, isCancelParameter, indexStartParameter, pageSizeParameter, sortFieldParameter, orderTypeParameter, searchDetailParameter);
        }
    
        public virtual ObjectResult<usp_ClonePeriod_Select_Result> usp_ClonePeriod_Select(Nullable<System.DateTime> payPeriod)
        {
            var payPeriodParameter = payPeriod.HasValue ?
                new ObjectParameter("payPeriod", payPeriod) :
                new ObjectParameter("payPeriod", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ClonePeriod_Select_Result>("usp_ClonePeriod_Select", payPeriodParameter);
        }
    
        public virtual ObjectResult<usp_DataSourceMaster_Generate_Result> usp_DataSourceMaster_Generate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_DataSourceMaster_Generate_Result>("usp_DataSourceMaster_Generate");
        }
    
        public virtual ObjectResult<usp_DataSourceMaster_Select_Result> usp_DataSourceMaster_Select(Nullable<int> indexStart, Nullable<int> pageSize, string sortField, string orderType, string searchDetail)
        {
            var indexStartParameter = indexStart.HasValue ?
                new ObjectParameter("IndexStart", indexStart) :
                new ObjectParameter("IndexStart", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortFieldParameter = sortField != null ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(string));
    
            var orderTypeParameter = orderType != null ?
                new ObjectParameter("OrderType", orderType) :
                new ObjectParameter("OrderType", typeof(string));
    
            var searchDetailParameter = searchDetail != null ?
                new ObjectParameter("SearchDetail", searchDetail) :
                new ObjectParameter("SearchDetail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_DataSourceMaster_Select_Result>("usp_DataSourceMaster_Select", indexStartParameter, pageSizeParameter, sortFieldParameter, orderTypeParameter, searchDetailParameter);
        }
    
        public virtual ObjectResult<usp_DataSourceMaster_Allowlist_Update_Result> usp_DataSourceMaster_Allowlist_Update(Nullable<int> dataSourceMasterId, string allowList, string updatedBy)
        {
            var dataSourceMasterIdParameter = dataSourceMasterId.HasValue ?
                new ObjectParameter("dataSourceMasterId", dataSourceMasterId) :
                new ObjectParameter("dataSourceMasterId", typeof(int));
    
            var allowListParameter = allowList != null ?
                new ObjectParameter("allowList", allowList) :
                new ObjectParameter("allowList", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("updatedBy", updatedBy) :
                new ObjectParameter("updatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_DataSourceMaster_Allowlist_Update_Result>("usp_DataSourceMaster_Allowlist_Update", dataSourceMasterIdParameter, allowListParameter, updatedByParameter);
        }
    
        public virtual ObjectResult<usp_Model_Description_Update_Result> usp_Model_Description_Update(Nullable<int> modelId, string description, string updatedBy)
        {
            var modelIdParameter = modelId.HasValue ?
                new ObjectParameter("modelId", modelId) :
                new ObjectParameter("modelId", typeof(int));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("updatedBy", updatedBy) :
                new ObjectParameter("updatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Model_Description_Update_Result>("usp_Model_Description_Update", modelIdParameter, descriptionParameter, updatedByParameter);
        }
    
        public virtual ObjectResult<usp_Model_Select_Result> usp_Model_Select(Nullable<int> modelId, Nullable<int> indexStart, Nullable<int> pageSize, string sortField, string orderType, string searchDetail)
        {
            var modelIdParameter = modelId.HasValue ?
                new ObjectParameter("modelId", modelId) :
                new ObjectParameter("modelId", typeof(int));
    
            var indexStartParameter = indexStart.HasValue ?
                new ObjectParameter("indexStart", indexStart) :
                new ObjectParameter("indexStart", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var sortFieldParameter = sortField != null ?
                new ObjectParameter("sortField", sortField) :
                new ObjectParameter("sortField", typeof(string));
    
            var orderTypeParameter = orderType != null ?
                new ObjectParameter("orderType", orderType) :
                new ObjectParameter("orderType", typeof(string));
    
            var searchDetailParameter = searchDetail != null ?
                new ObjectParameter("searchDetail", searchDetail) :
                new ObjectParameter("searchDetail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Model_Select_Result>("usp_Model_Select", modelIdParameter, indexStartParameter, pageSizeParameter, sortFieldParameter, orderTypeParameter, searchDetailParameter);
        }
    
        public virtual ObjectResult<usp_ModelParameterDescription_Generate_Result> usp_ModelParameterDescription_Generate(Nullable<int> modelId)
        {
            var modelIdParameter = modelId.HasValue ?
                new ObjectParameter("modelId", modelId) :
                new ObjectParameter("modelId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ModelParameterDescription_Generate_Result>("usp_ModelParameterDescription_Generate", modelIdParameter);
        }
    
        public virtual ObjectResult<usp_ModelParameterDescription_Select_Result> usp_ModelParameterDescription_Select(Nullable<int> modelId, Nullable<int> indexStart, Nullable<int> pageSize, string sortField, string orderType, string searchDetail)
        {
            var modelIdParameter = modelId.HasValue ?
                new ObjectParameter("modelId", modelId) :
                new ObjectParameter("modelId", typeof(int));
    
            var indexStartParameter = indexStart.HasValue ?
                new ObjectParameter("indexStart", indexStart) :
                new ObjectParameter("indexStart", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var sortFieldParameter = sortField != null ?
                new ObjectParameter("sortField", sortField) :
                new ObjectParameter("sortField", typeof(string));
    
            var orderTypeParameter = orderType != null ?
                new ObjectParameter("orderType", orderType) :
                new ObjectParameter("orderType", typeof(string));
    
            var searchDetailParameter = searchDetail != null ?
                new ObjectParameter("searchDetail", searchDetail) :
                new ObjectParameter("searchDetail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ModelParameterDescription_Select_Result>("usp_ModelParameterDescription_Select", modelIdParameter, indexStartParameter, pageSizeParameter, sortFieldParameter, orderTypeParameter, searchDetailParameter);
        }
    
        public virtual ObjectResult<usp_ModelParameterDescription_Update_Result> usp_ModelParameterDescription_Update(Nullable<int> modelParameterDescriptionId, string description, string updateBy)
        {
            var modelParameterDescriptionIdParameter = modelParameterDescriptionId.HasValue ?
                new ObjectParameter("modelParameterDescriptionId", modelParameterDescriptionId) :
                new ObjectParameter("modelParameterDescriptionId", typeof(int));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var updateByParameter = updateBy != null ?
                new ObjectParameter("updateBy", updateBy) :
                new ObjectParameter("updateBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ModelParameterDescription_Update_Result>("usp_ModelParameterDescription_Update", modelParameterDescriptionIdParameter, descriptionParameter, updateByParameter);
        }
    
        public virtual ObjectResult<usp_CommissionPeriod_GetLastedPeriod_Select_Result> usp_CommissionPeriod_GetLastedPeriod_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CommissionPeriod_GetLastedPeriod_Select_Result>("usp_CommissionPeriod_GetLastedPeriod_Select");
        }
    
        public virtual ObjectResult<usp_ModelDatasouce_Select_Result> usp_ModelDatasouce_Select(Nullable<int> periodId, Nullable<int> indexStart, Nullable<int> pageSize, string sortField, string orderType, string searchDetail)
        {
            var periodIdParameter = periodId.HasValue ?
                new ObjectParameter("PeriodId", periodId) :
                new ObjectParameter("PeriodId", typeof(int));
    
            var indexStartParameter = indexStart.HasValue ?
                new ObjectParameter("IndexStart", indexStart) :
                new ObjectParameter("IndexStart", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortFieldParameter = sortField != null ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(string));
    
            var orderTypeParameter = orderType != null ?
                new ObjectParameter("OrderType", orderType) :
                new ObjectParameter("OrderType", typeof(string));
    
            var searchDetailParameter = searchDetail != null ?
                new ObjectParameter("SearchDetail", searchDetail) :
                new ObjectParameter("SearchDetail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ModelDatasouce_Select_Result>("usp_ModelDatasouce_Select", periodIdParameter, indexStartParameter, pageSizeParameter, sortFieldParameter, orderTypeParameter, searchDetailParameter);
        }
    
        public virtual ObjectResult<string> usp_GetTableName()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_GetTableName");
        }
    
        public virtual ObjectResult<usp_ModelCalculationIndex_ReOrder_Update_Result> usp_ModelCalculationIndex_ReOrder_Update(Nullable<int> modelCalculationIndexId, Nullable<int> no, string updatedBy)
        {
            var modelCalculationIndexIdParameter = modelCalculationIndexId.HasValue ?
                new ObjectParameter("modelCalculationIndexId", modelCalculationIndexId) :
                new ObjectParameter("modelCalculationIndexId", typeof(int));
    
            var noParameter = no.HasValue ?
                new ObjectParameter("no", no) :
                new ObjectParameter("no", typeof(int));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("updatedBy", updatedBy) :
                new ObjectParameter("updatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ModelCalculationIndex_ReOrder_Update_Result>("usp_ModelCalculationIndex_ReOrder_Update", modelCalculationIndexIdParameter, noParameter, updatedByParameter);
        }
    
        public virtual ObjectResult<usp_ModelCalculationIndex_Select_Result> usp_ModelCalculationIndex_Select(Nullable<int> periodId, Nullable<int> indexStart, Nullable<int> pageSize, string sortField, string orderType, string searchDetail)
        {
            var periodIdParameter = periodId.HasValue ?
                new ObjectParameter("periodId", periodId) :
                new ObjectParameter("periodId", typeof(int));
    
            var indexStartParameter = indexStart.HasValue ?
                new ObjectParameter("IndexStart", indexStart) :
                new ObjectParameter("IndexStart", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortFieldParameter = sortField != null ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(string));
    
            var orderTypeParameter = orderType != null ?
                new ObjectParameter("OrderType", orderType) :
                new ObjectParameter("OrderType", typeof(string));
    
            var searchDetailParameter = searchDetail != null ?
                new ObjectParameter("SearchDetail", searchDetail) :
                new ObjectParameter("SearchDetail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ModelCalculationIndex_Select_Result>("usp_ModelCalculationIndex_Select", periodIdParameter, indexStartParameter, pageSizeParameter, sortFieldParameter, orderTypeParameter, searchDetailParameter);
        }
    
        public virtual ObjectResult<usp_ModelCalculationIndex_Delete_Result> usp_ModelCalculationIndex_Delete(Nullable<int> modelCalculationIndexId, string deletedBy)
        {
            var modelCalculationIndexIdParameter = modelCalculationIndexId.HasValue ?
                new ObjectParameter("modelCalculationIndexId", modelCalculationIndexId) :
                new ObjectParameter("modelCalculationIndexId", typeof(int));
    
            var deletedByParameter = deletedBy != null ?
                new ObjectParameter("deletedBy", deletedBy) :
                new ObjectParameter("deletedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ModelCalculationIndex_Delete_Result>("usp_ModelCalculationIndex_Delete", modelCalculationIndexIdParameter, deletedByParameter);
        }
    
        public virtual ObjectResult<usp_ParamValue_Select_Result> usp_ParamValue_Select(Nullable<int> periodId, string mainKey, Nullable<int> indexStart, Nullable<int> pageSize, string sortField, string orderType, string searchDetail)
        {
            var periodIdParameter = periodId.HasValue ?
                new ObjectParameter("periodId", periodId) :
                new ObjectParameter("periodId", typeof(int));
    
            var mainKeyParameter = mainKey != null ?
                new ObjectParameter("mainKey", mainKey) :
                new ObjectParameter("mainKey", typeof(string));
    
            var indexStartParameter = indexStart.HasValue ?
                new ObjectParameter("IndexStart", indexStart) :
                new ObjectParameter("IndexStart", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortFieldParameter = sortField != null ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(string));
    
            var orderTypeParameter = orderType != null ?
                new ObjectParameter("OrderType", orderType) :
                new ObjectParameter("OrderType", typeof(string));
    
            var searchDetailParameter = searchDetail != null ?
                new ObjectParameter("SearchDetail", searchDetail) :
                new ObjectParameter("SearchDetail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ParamValue_Select_Result>("usp_ParamValue_Select", periodIdParameter, mainKeyParameter, indexStartParameter, pageSizeParameter, sortFieldParameter, orderTypeParameter, searchDetailParameter);
        }
    
        public virtual ObjectResult<usp_AppDetailPH_Select_Result> usp_AppDetailPH_Select(Nullable<int> periodId, string sale_Id1, Nullable<int> indexStart, Nullable<int> pageSize, string sortField, string orderType, string searchDetail)
        {
            var periodIdParameter = periodId.HasValue ?
                new ObjectParameter("periodId", periodId) :
                new ObjectParameter("periodId", typeof(int));
    
            var sale_Id1Parameter = sale_Id1 != null ?
                new ObjectParameter("sale_Id1", sale_Id1) :
                new ObjectParameter("sale_Id1", typeof(string));
    
            var indexStartParameter = indexStart.HasValue ?
                new ObjectParameter("indexStart", indexStart) :
                new ObjectParameter("indexStart", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var sortFieldParameter = sortField != null ?
                new ObjectParameter("sortField", sortField) :
                new ObjectParameter("sortField", typeof(string));
    
            var orderTypeParameter = orderType != null ?
                new ObjectParameter("orderType", orderType) :
                new ObjectParameter("orderType", typeof(string));
    
            var searchDetailParameter = searchDetail != null ?
                new ObjectParameter("searchDetail", searchDetail) :
                new ObjectParameter("searchDetail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_AppDetailPH_Select_Result>("usp_AppDetailPH_Select", periodIdParameter, sale_Id1Parameter, indexStartParameter, pageSizeParameter, sortFieldParameter, orderTypeParameter, searchDetailParameter);
        }
    
        public virtual ObjectResult<usp_AppDetailHP_Select_Result> usp_AppDetailHP_Select(Nullable<int> periodId, string sale_Id1, Nullable<int> indexStart, Nullable<int> pageSize, string sortField, string orderType, string searchDetail)
        {
            var periodIdParameter = periodId.HasValue ?
                new ObjectParameter("periodId", periodId) :
                new ObjectParameter("periodId", typeof(int));
    
            var sale_Id1Parameter = sale_Id1 != null ?
                new ObjectParameter("sale_Id1", sale_Id1) :
                new ObjectParameter("sale_Id1", typeof(string));
    
            var indexStartParameter = indexStart.HasValue ?
                new ObjectParameter("indexStart", indexStart) :
                new ObjectParameter("indexStart", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var sortFieldParameter = sortField != null ?
                new ObjectParameter("sortField", sortField) :
                new ObjectParameter("sortField", typeof(string));
    
            var orderTypeParameter = orderType != null ?
                new ObjectParameter("orderType", orderType) :
                new ObjectParameter("orderType", typeof(string));
    
            var searchDetailParameter = searchDetail != null ?
                new ObjectParameter("searchDetail", searchDetail) :
                new ObjectParameter("searchDetail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_AppDetailHP_Select_Result>("usp_AppDetailHP_Select", periodIdParameter, sale_Id1Parameter, indexStartParameter, pageSizeParameter, sortFieldParameter, orderTypeParameter, searchDetailParameter);
        }
    
        public virtual ObjectResult<usp_AppDetailPA30_Select_Result> usp_AppDetailPA30_Select(Nullable<int> periodId, string sale_Id1, Nullable<int> indexStart, Nullable<int> pageSize, string sortField, string orderType, string searchDetail)
        {
            var periodIdParameter = periodId.HasValue ?
                new ObjectParameter("periodId", periodId) :
                new ObjectParameter("periodId", typeof(int));
    
            var sale_Id1Parameter = sale_Id1 != null ?
                new ObjectParameter("sale_Id1", sale_Id1) :
                new ObjectParameter("sale_Id1", typeof(string));
    
            var indexStartParameter = indexStart.HasValue ?
                new ObjectParameter("indexStart", indexStart) :
                new ObjectParameter("indexStart", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var sortFieldParameter = sortField != null ?
                new ObjectParameter("sortField", sortField) :
                new ObjectParameter("sortField", typeof(string));
    
            var orderTypeParameter = orderType != null ?
                new ObjectParameter("orderType", orderType) :
                new ObjectParameter("orderType", typeof(string));
    
            var searchDetailParameter = searchDetail != null ?
                new ObjectParameter("searchDetail", searchDetail) :
                new ObjectParameter("searchDetail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_AppDetailPA30_Select_Result>("usp_AppDetailPA30_Select", periodIdParameter, sale_Id1Parameter, indexStartParameter, pageSizeParameter, sortFieldParameter, orderTypeParameter, searchDetailParameter);
        }
    
        public virtual ObjectResult<usp_AppDetailPAcommunity_Select_Result> usp_AppDetailPAcommunity_Select(Nullable<int> periodId, string sale_Id1, Nullable<int> indexStart, Nullable<int> pageSize, string sortField, string orderType, string searchDetail)
        {
            var periodIdParameter = periodId.HasValue ?
                new ObjectParameter("periodId", periodId) :
                new ObjectParameter("periodId", typeof(int));
    
            var sale_Id1Parameter = sale_Id1 != null ?
                new ObjectParameter("sale_Id1", sale_Id1) :
                new ObjectParameter("sale_Id1", typeof(string));
    
            var indexStartParameter = indexStart.HasValue ?
                new ObjectParameter("indexStart", indexStart) :
                new ObjectParameter("indexStart", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var sortFieldParameter = sortField != null ?
                new ObjectParameter("sortField", sortField) :
                new ObjectParameter("sortField", typeof(string));
    
            var orderTypeParameter = orderType != null ?
                new ObjectParameter("orderType", orderType) :
                new ObjectParameter("orderType", typeof(string));
    
            var searchDetailParameter = searchDetail != null ?
                new ObjectParameter("searchDetail", searchDetail) :
                new ObjectParameter("searchDetail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_AppDetailPAcommunity_Select_Result>("usp_AppDetailPAcommunity_Select", periodIdParameter, sale_Id1Parameter, indexStartParameter, pageSizeParameter, sortFieldParameter, orderTypeParameter, searchDetailParameter);
        }
    
        public virtual ObjectResult<usp_AppDetailPL_Select_Result> usp_AppDetailPL_Select(Nullable<int> periodId, string sale_Id1, Nullable<int> indexStart, Nullable<int> pageSize, string sortField, string orderType, string searchDetail)
        {
            var periodIdParameter = periodId.HasValue ?
                new ObjectParameter("periodId", periodId) :
                new ObjectParameter("periodId", typeof(int));
    
            var sale_Id1Parameter = sale_Id1 != null ?
                new ObjectParameter("sale_Id1", sale_Id1) :
                new ObjectParameter("sale_Id1", typeof(string));
    
            var indexStartParameter = indexStart.HasValue ?
                new ObjectParameter("indexStart", indexStart) :
                new ObjectParameter("indexStart", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var sortFieldParameter = sortField != null ?
                new ObjectParameter("sortField", sortField) :
                new ObjectParameter("sortField", typeof(string));
    
            var orderTypeParameter = orderType != null ?
                new ObjectParameter("orderType", orderType) :
                new ObjectParameter("orderType", typeof(string));
    
            var searchDetailParameter = searchDetail != null ?
                new ObjectParameter("searchDetail", searchDetail) :
                new ObjectParameter("searchDetail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_AppDetailPL_Select_Result>("usp_AppDetailPL_Select", periodIdParameter, sale_Id1Parameter, indexStartParameter, pageSizeParameter, sortFieldParameter, orderTypeParameter, searchDetailParameter);
        }
    
        public virtual ObjectResult<usp_Lapse_Select_Result> usp_Lapse_Select(Nullable<int> periodId, string sale_Id1, Nullable<int> indexStart, Nullable<int> pageSize, string sortField, string orderType, string searchDetail)
        {
            var periodIdParameter = periodId.HasValue ?
                new ObjectParameter("periodId", periodId) :
                new ObjectParameter("periodId", typeof(int));
    
            var sale_Id1Parameter = sale_Id1 != null ?
                new ObjectParameter("sale_Id1", sale_Id1) :
                new ObjectParameter("sale_Id1", typeof(string));
    
            var indexStartParameter = indexStart.HasValue ?
                new ObjectParameter("indexStart", indexStart) :
                new ObjectParameter("indexStart", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var sortFieldParameter = sortField != null ?
                new ObjectParameter("sortField", sortField) :
                new ObjectParameter("sortField", typeof(string));
    
            var orderTypeParameter = orderType != null ?
                new ObjectParameter("orderType", orderType) :
                new ObjectParameter("orderType", typeof(string));
    
            var searchDetailParameter = searchDetail != null ?
                new ObjectParameter("searchDetail", searchDetail) :
                new ObjectParameter("searchDetail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Lapse_Select_Result>("usp_Lapse_Select", periodIdParameter, sale_Id1Parameter, indexStartParameter, pageSizeParameter, sortFieldParameter, orderTypeParameter, searchDetailParameter);
        }
    
        public virtual ObjectResult<usp_AppDetailMP_Select_Result> usp_AppDetailMP_Select(Nullable<int> periodId, string sale_Id1, Nullable<int> indexStart, Nullable<int> pageSize, string sortField, string orderType, string searchDetail)
        {
            var periodIdParameter = periodId.HasValue ?
                new ObjectParameter("periodId", periodId) :
                new ObjectParameter("periodId", typeof(int));
    
            var sale_Id1Parameter = sale_Id1 != null ?
                new ObjectParameter("sale_Id1", sale_Id1) :
                new ObjectParameter("sale_Id1", typeof(string));
    
            var indexStartParameter = indexStart.HasValue ?
                new ObjectParameter("indexStart", indexStart) :
                new ObjectParameter("indexStart", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var sortFieldParameter = sortField != null ?
                new ObjectParameter("sortField", sortField) :
                new ObjectParameter("sortField", typeof(string));
    
            var orderTypeParameter = orderType != null ?
                new ObjectParameter("orderType", orderType) :
                new ObjectParameter("orderType", typeof(string));
    
            var searchDetailParameter = searchDetail != null ?
                new ObjectParameter("searchDetail", searchDetail) :
                new ObjectParameter("searchDetail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_AppDetailMP_Select_Result>("usp_AppDetailMP_Select", periodIdParameter, sale_Id1Parameter, indexStartParameter, pageSizeParameter, sortFieldParameter, orderTypeParameter, searchDetailParameter);
        }
    
        public virtual ObjectResult<usp_DatasourceImportedLog_Select_Result> usp_DatasourceImportedLog_Select(Nullable<int> periodId, string importBy, Nullable<int> indexStart, Nullable<int> pageSize, string sortField, string orderType, string searchDetail)
        {
            var periodIdParameter = periodId.HasValue ?
                new ObjectParameter("periodId", periodId) :
                new ObjectParameter("periodId", typeof(int));
    
            var importByParameter = importBy != null ?
                new ObjectParameter("importBy", importBy) :
                new ObjectParameter("importBy", typeof(string));
    
            var indexStartParameter = indexStart.HasValue ?
                new ObjectParameter("IndexStart", indexStart) :
                new ObjectParameter("IndexStart", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortFieldParameter = sortField != null ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(string));
    
            var orderTypeParameter = orderType != null ?
                new ObjectParameter("OrderType", orderType) :
                new ObjectParameter("OrderType", typeof(string));
    
            var searchDetailParameter = searchDetail != null ?
                new ObjectParameter("SearchDetail", searchDetail) :
                new ObjectParameter("SearchDetail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_DatasourceImportedLog_Select_Result>("usp_DatasourceImportedLog_Select", periodIdParameter, importByParameter, indexStartParameter, pageSizeParameter, sortFieldParameter, orderTypeParameter, searchDetailParameter);
        }
    
        public virtual int usp_GetDatasourceByTableNameAndPeriodId(string tableName, string period_Id)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("tableName", tableName) :
                new ObjectParameter("tableName", typeof(string));
    
            var period_IdParameter = period_Id != null ?
                new ObjectParameter("period_Id", period_Id) :
                new ObjectParameter("period_Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_GetDatasourceByTableNameAndPeriodId", tableNameParameter, period_IdParameter);
        }
    
        public virtual ObjectResult<usp_DatasourceImportedEditCause_Select_Result> usp_DatasourceImportedEditCause_Select(Nullable<int> id, Nullable<int> indexStart, Nullable<int> pageSize, string sortField, string orderType, string searchDetail)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var indexStartParameter = indexStart.HasValue ?
                new ObjectParameter("IndexStart", indexStart) :
                new ObjectParameter("IndexStart", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortFieldParameter = sortField != null ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(string));
    
            var orderTypeParameter = orderType != null ?
                new ObjectParameter("OrderType", orderType) :
                new ObjectParameter("OrderType", typeof(string));
    
            var searchDetailParameter = searchDetail != null ?
                new ObjectParameter("SearchDetail", searchDetail) :
                new ObjectParameter("SearchDetail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_DatasourceImportedEditCause_Select_Result>("usp_DatasourceImportedEditCause_Select", idParameter, indexStartParameter, pageSizeParameter, sortFieldParameter, orderTypeParameter, searchDetailParameter);
        }
    
        public virtual ObjectResult<usp_DatasourceImportedLog_Notify_Select_Result> usp_DatasourceImportedLog_Notify_Select(Nullable<int> periodId, string importBy, Nullable<int> indexStart, Nullable<int> pageSize, string sortField, string orderType, string searchDetail)
        {
            var periodIdParameter = periodId.HasValue ?
                new ObjectParameter("periodId", periodId) :
                new ObjectParameter("periodId", typeof(int));
    
            var importByParameter = importBy != null ?
                new ObjectParameter("importBy", importBy) :
                new ObjectParameter("importBy", typeof(string));
    
            var indexStartParameter = indexStart.HasValue ?
                new ObjectParameter("IndexStart", indexStart) :
                new ObjectParameter("IndexStart", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortFieldParameter = sortField != null ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(string));
    
            var orderTypeParameter = orderType != null ?
                new ObjectParameter("OrderType", orderType) :
                new ObjectParameter("OrderType", typeof(string));
    
            var searchDetailParameter = searchDetail != null ?
                new ObjectParameter("SearchDetail", searchDetail) :
                new ObjectParameter("SearchDetail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_DatasourceImportedLog_Notify_Select_Result>("usp_DatasourceImportedLog_Notify_Select", periodIdParameter, importByParameter, indexStartParameter, pageSizeParameter, sortFieldParameter, orderTypeParameter, searchDetailParameter);
        }
    
        public virtual ObjectResult<usp_DatasourceImportedLog_Notify_Update_Result> usp_DatasourceImportedLog_Notify_Update(Nullable<int> datasourceImportedLogId, Nullable<int> editCase_Id, string editRemark, string editBy)
        {
            var datasourceImportedLogIdParameter = datasourceImportedLogId.HasValue ?
                new ObjectParameter("datasourceImportedLogId", datasourceImportedLogId) :
                new ObjectParameter("datasourceImportedLogId", typeof(int));
    
            var editCase_IdParameter = editCase_Id.HasValue ?
                new ObjectParameter("editCase_Id", editCase_Id) :
                new ObjectParameter("editCase_Id", typeof(int));
    
            var editRemarkParameter = editRemark != null ?
                new ObjectParameter("editRemark", editRemark) :
                new ObjectParameter("editRemark", typeof(string));
    
            var editByParameter = editBy != null ?
                new ObjectParameter("editBy", editBy) :
                new ObjectParameter("editBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_DatasourceImportedLog_Notify_Update_Result>("usp_DatasourceImportedLog_Notify_Update", datasourceImportedLogIdParameter, editCase_IdParameter, editRemarkParameter, editByParameter);
        }
    
        public virtual ObjectResult<usp_ApplyDesignerToCalculationIndex_Result> usp_ApplyDesignerToCalculationIndex(Nullable<int> designerModelId, Nullable<int> periodId, string createdBy)
        {
            var designerModelIdParameter = designerModelId.HasValue ?
                new ObjectParameter("designerModelId", designerModelId) :
                new ObjectParameter("designerModelId", typeof(int));
    
            var periodIdParameter = periodId.HasValue ?
                new ObjectParameter("periodId", periodId) :
                new ObjectParameter("periodId", typeof(int));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("createdBy", createdBy) :
                new ObjectParameter("createdBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ApplyDesignerToCalculationIndex_Result>("usp_ApplyDesignerToCalculationIndex", designerModelIdParameter, periodIdParameter, createdByParameter);
        }
    
        public virtual ObjectResult<usp_ApplyDesignerToCalculationIndex_Select_Result> usp_ApplyDesignerToCalculationIndex_Select(Nullable<int> periodId, Nullable<int> indexStart, Nullable<int> pageSize, string sortField, string orderType, string searchDetail)
        {
            var periodIdParameter = periodId.HasValue ?
                new ObjectParameter("periodId", periodId) :
                new ObjectParameter("periodId", typeof(int));
    
            var indexStartParameter = indexStart.HasValue ?
                new ObjectParameter("indexStart", indexStart) :
                new ObjectParameter("indexStart", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var sortFieldParameter = sortField != null ?
                new ObjectParameter("sortField", sortField) :
                new ObjectParameter("sortField", typeof(string));
    
            var orderTypeParameter = orderType != null ?
                new ObjectParameter("orderType", orderType) :
                new ObjectParameter("orderType", typeof(string));
    
            var searchDetailParameter = searchDetail != null ?
                new ObjectParameter("searchDetail", searchDetail) :
                new ObjectParameter("searchDetail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ApplyDesignerToCalculationIndex_Select_Result>("usp_ApplyDesignerToCalculationIndex_Select", periodIdParameter, indexStartParameter, pageSizeParameter, sortFieldParameter, orderTypeParameter, searchDetailParameter);
        }
    
        public virtual ObjectResult<usp_DesignModel_GetConfigForCreateSheet_Result> usp_DesignModel_GetConfigForCreateSheet(Nullable<int> designModelNameId)
        {
            var designModelNameIdParameter = designModelNameId.HasValue ?
                new ObjectParameter("designModelNameId", designModelNameId) :
                new ObjectParameter("designModelNameId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_DesignModel_GetConfigForCreateSheet_Result>("usp_DesignModel_GetConfigForCreateSheet", designModelNameIdParameter);
        }
    
        public virtual int usp_ApplyDesignerToCalculationIndex_AlterColumn(Nullable<int> designerModel_Id)
        {
            var designerModel_IdParameter = designerModel_Id.HasValue ?
                new ObjectParameter("designerModel_Id", designerModel_Id) :
                new ObjectParameter("designerModel_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ApplyDesignerToCalculationIndex_AlterColumn", designerModel_IdParameter);
        }
    
        public virtual int usp_ApplyDesignerToCalculationIndex_CreateTable(Nullable<int> designerModel_Id)
        {
            var designerModel_IdParameter = designerModel_Id.HasValue ?
                new ObjectParameter("designerModel_Id", designerModel_Id) :
                new ObjectParameter("designerModel_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ApplyDesignerToCalculationIndex_CreateTable", designerModel_IdParameter);
        }
    
        public virtual int usp_CreateUpdateDesignerTable(Nullable<int> designerModel_Id)
        {
            var designerModel_IdParameter = designerModel_Id.HasValue ?
                new ObjectParameter("designerModel_Id", designerModel_Id) :
                new ObjectParameter("designerModel_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CreateUpdateDesignerTable", designerModel_IdParameter);
        }
    
        public virtual ObjectResult<usp_DatasourceImportedLogManual_Update_Result> usp_DatasourceImportedLogManual_Update(Nullable<int> periodId, string datasourceName, string updatedBy)
        {
            var periodIdParameter = periodId.HasValue ?
                new ObjectParameter("PeriodId", periodId) :
                new ObjectParameter("PeriodId", typeof(int));
    
            var datasourceNameParameter = datasourceName != null ?
                new ObjectParameter("DatasourceName", datasourceName) :
                new ObjectParameter("DatasourceName", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_DatasourceImportedLogManual_Update_Result>("usp_DatasourceImportedLogManual_Update", periodIdParameter, datasourceNameParameter, updatedByParameter);
        }
    
        public virtual int usp_DesignerModel_Delete(Nullable<int> designerModel_Id)
        {
            var designerModel_IdParameter = designerModel_Id.HasValue ?
                new ObjectParameter("designerModel_Id", designerModel_Id) :
                new ObjectParameter("designerModel_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DesignerModel_Delete", designerModel_IdParameter);
        }
    
        public virtual int usp_DesignModel_ClearDatasource(Nullable<int> designerModel_Id)
        {
            var designerModel_IdParameter = designerModel_Id.HasValue ?
                new ObjectParameter("designerModel_Id", designerModel_Id) :
                new ObjectParameter("designerModel_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DesignModel_ClearDatasource", designerModel_IdParameter);
        }
    
        public virtual ObjectResult<usp_DesignModel_Configuration_Datatable_Result> usp_DesignModel_Configuration_Datatable(string criteria, Nullable<int> pageStart, Nullable<int> pageSize, string sortField, string orderType, Nullable<int> designModel_Id)
        {
            var criteriaParameter = criteria != null ?
                new ObjectParameter("criteria", criteria) :
                new ObjectParameter("criteria", typeof(string));
    
            var pageStartParameter = pageStart.HasValue ?
                new ObjectParameter("pageStart", pageStart) :
                new ObjectParameter("pageStart", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var sortFieldParameter = sortField != null ?
                new ObjectParameter("sortField", sortField) :
                new ObjectParameter("sortField", typeof(string));
    
            var orderTypeParameter = orderType != null ?
                new ObjectParameter("orderType", orderType) :
                new ObjectParameter("orderType", typeof(string));
    
            var designModel_IdParameter = designModel_Id.HasValue ?
                new ObjectParameter("DesignModel_Id", designModel_Id) :
                new ObjectParameter("DesignModel_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_DesignModel_Configuration_Datatable_Result>("usp_DesignModel_Configuration_Datatable", criteriaParameter, pageStartParameter, pageSizeParameter, sortFieldParameter, orderTypeParameter, designModel_IdParameter);
        }
    
        public virtual ObjectResult<usp_DesignModel_Datasource_Get_Result> usp_DesignModel_Datasource_Get(Nullable<int> desingerModel_Id)
        {
            var desingerModel_IdParameter = desingerModel_Id.HasValue ?
                new ObjectParameter("DesingerModel_Id", desingerModel_Id) :
                new ObjectParameter("DesingerModel_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_DesignModel_Datasource_Get_Result>("usp_DesignModel_Datasource_Get", desingerModel_IdParameter);
        }
    
        public virtual ObjectResult<string> usp_DesignModel_GetMainKey(string mainkeyDatasourceName)
        {
            var mainkeyDatasourceNameParameter = mainkeyDatasourceName != null ?
                new ObjectParameter("mainkeyDatasourceName", mainkeyDatasourceName) :
                new ObjectParameter("mainkeyDatasourceName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_DesignModel_GetMainKey", mainkeyDatasourceNameParameter);
        }
    
        public virtual ObjectResult<usp_DesignModel_Parameter_Datatable_Result> usp_DesignModel_Parameter_Datatable(string criteria, Nullable<int> pageStart, Nullable<int> pageSize, string sortField, string orderType, Nullable<int> designModel_Id)
        {
            var criteriaParameter = criteria != null ?
                new ObjectParameter("criteria", criteria) :
                new ObjectParameter("criteria", typeof(string));
    
            var pageStartParameter = pageStart.HasValue ?
                new ObjectParameter("pageStart", pageStart) :
                new ObjectParameter("pageStart", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var sortFieldParameter = sortField != null ?
                new ObjectParameter("sortField", sortField) :
                new ObjectParameter("sortField", typeof(string));
    
            var orderTypeParameter = orderType != null ?
                new ObjectParameter("orderType", orderType) :
                new ObjectParameter("orderType", typeof(string));
    
            var designModel_IdParameter = designModel_Id.HasValue ?
                new ObjectParameter("designModel_Id", designModel_Id) :
                new ObjectParameter("designModel_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_DesignModel_Parameter_Datatable_Result>("usp_DesignModel_Parameter_Datatable", criteriaParameter, pageStartParameter, pageSizeParameter, sortFieldParameter, orderTypeParameter, designModel_IdParameter);
        }
    
        public virtual int usp_DesignModel_ReCalculate(Nullable<int> designerModel_Id)
        {
            var designerModel_IdParameter = designerModel_Id.HasValue ?
                new ObjectParameter("designerModel_Id", designerModel_Id) :
                new ObjectParameter("designerModel_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DesignModel_ReCalculate", designerModel_IdParameter);
        }
    
        public virtual ObjectResult<usp_GetCommissionPeriod_Result> usp_GetCommissionPeriod(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetCommissionPeriod_Result>("usp_GetCommissionPeriod", idParameter);
        }
    
        public virtual ObjectResult<usp_GetConfigForCreateSheet_Result> usp_GetConfigForCreateSheet(Nullable<int> period_Id, Nullable<int> model_Id)
        {
            var period_IdParameter = period_Id.HasValue ?
                new ObjectParameter("period_Id", period_Id) :
                new ObjectParameter("period_Id", typeof(int));
    
            var model_IdParameter = model_Id.HasValue ?
                new ObjectParameter("model_Id", model_Id) :
                new ObjectParameter("model_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetConfigForCreateSheet_Result>("usp_GetConfigForCreateSheet", period_IdParameter, model_IdParameter);
        }
    
        public virtual ObjectResult<string> usp_GetDatasourceTableName()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_GetDatasourceTableName");
        }
    
        public virtual int usp_SaveCalculatedParams(Nullable<int> period_Id)
        {
            var period_IdParameter = period_Id.HasValue ?
                new ObjectParameter("Period_Id", period_Id) :
                new ObjectParameter("Period_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_SaveCalculatedParams", period_IdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_GetAvailablePeriodForDesigner(string tableName)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("tableName", tableName) :
                new ObjectParameter("tableName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_GetAvailablePeriodForDesigner", tableNameParameter);
        }
    
        public virtual ObjectResult<usp_DesignModel_Datatable_Result1> usp_DesignModel_Datatable(string criteria, Nullable<int> pageStart, Nullable<int> pageSize, string sortField, string orderType)
        {
            var criteriaParameter = criteria != null ?
                new ObjectParameter("criteria", criteria) :
                new ObjectParameter("criteria", typeof(string));
    
            var pageStartParameter = pageStart.HasValue ?
                new ObjectParameter("pageStart", pageStart) :
                new ObjectParameter("pageStart", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var sortFieldParameter = sortField != null ?
                new ObjectParameter("sortField", sortField) :
                new ObjectParameter("sortField", typeof(string));
    
            var orderTypeParameter = orderType != null ?
                new ObjectParameter("orderType", orderType) :
                new ObjectParameter("orderType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_DesignModel_Datatable_Result1>("usp_DesignModel_Datatable", criteriaParameter, pageStartParameter, pageSizeParameter, sortFieldParameter, orderTypeParameter);
        }
    
        public virtual int usp_CloneCalculationMethod(Nullable<int> fromPeriodId, Nullable<int> toPeriodId)
        {
            var fromPeriodIdParameter = fromPeriodId.HasValue ?
                new ObjectParameter("FromPeriodId", fromPeriodId) :
                new ObjectParameter("FromPeriodId", typeof(int));
    
            var toPeriodIdParameter = toPeriodId.HasValue ?
                new ObjectParameter("ToPeriodId", toPeriodId) :
                new ObjectParameter("ToPeriodId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CloneCalculationMethod", fromPeriodIdParameter, toPeriodIdParameter);
        }
    }
}
