//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSCommission.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_Area_Calculation_LastMonth
    {
        public int Id { get; set; }
        public Nullable<int> Period_Id { get; set; }
        public string MainKey { get; set; }
        public string Area { get; set; }
        public Nullable<double> Best_Loss_Claim_Area { get; set; }
        public Nullable<double> Best_Lapse_Area { get; set; }
        public Nullable<int> Balance_All_LastMonth { get; set; }
        public Nullable<int> Balance_PH_All_LastMonth { get; set; }
        public Nullable<int> Balance_MP_All_LastMonth { get; set; }
    }
}
