//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSCommission.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_Zebra_Calculation_LastMonth
    {
        public int Id { get; set; }
        public Nullable<int> Period_Id { get; set; }
        public string MainKey { get; set; }
        public string ZebraNumber { get; set; }
        public Nullable<double> Lapse_Adjust_PH_LastMonth { get; set; }
        public Nullable<double> Lapse_Adjust_PH_InProcess_LastMonth { get; set; }
        public Nullable<double> Best_Loss_Claim_Zebra { get; set; }
    }
}
