//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSCommission.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesignerModelConfig
    {
        public int Id { get; set; }
        public Nullable<int> DesignerModel_Id { get; set; }
        public Nullable<int> ConfigIndex { get; set; }
        public string ConfigName { get; set; }
        public string ConfigFrom { get; set; }
        public string ConfigTo { get; set; }
        public string ConfigValue { get; set; }
        public string ConfigDescription { get; set; }
    
        public virtual DesignerModel DesignerModel { get; set; }
    }
}
