//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSSurvey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyResultAnswer
    {
        public int SurveyResultAnswerId { get; set; }
        public Nullable<int> SurveyResultId { get; set; }
        public Nullable<int> SurveyAnswerId { get; set; }
        public Nullable<int> AnswerId { get; set; }
        public string AnswerMore { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual SurveyResult SurveyResult { get; set; }
    }
}
