//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSBankDirectDebit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankDirectDebitPrintLog
    {
        public int BankDirectDebitPrintLogId { get; set; }
        public int BankDirectDebitHeaderId { get; set; }
        public Nullable<int> CreateByUserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual BankDirectDebitHeader BankDirectDebitHeader { get; set; }
    }
}
