//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSBankDirectDebit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTBTransactionStatu
    {
        public int KTBTransactionStatusId { get; set; }
        public string KTBTransactionStatusCode { get; set; }
        public string KTBTransactionStatus { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreateByUserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateByUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
