//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSClaimOnLine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccount
    {
        public int BankAccountId { get; set; }
        public string AccountNo { get; set; }
        public string BankId { get; set; }
        public string BankName { get; set; }
        public decimal Balance { get; set; }
        public bool IsActive { get; set; }
        public string CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedByUserId { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
