//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSAudioPlayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoiceRecordURLRequest
    {
        public System.Guid Id { get; set; }
        public int VoiceRecordDetailId { get; set; }
        public string VoiceRecordDetailURL { get; set; }
        public string ResponseURL { get; set; }
        public System.DateTime CreatedDatetime { get; set; }
        public System.DateTime ExpireDatetime { get; set; }
    
        public virtual VoiceRecordDetail VoiceRecordDetail { get; set; }
    }
}
