//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSCriticalIllness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrAppDetail
    {
        public int TrAppDetailId { get; set; }
        public Nullable<int> TrAppHeaderId { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public string ApplicationCode { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ProductCode { get; set; }
        public string Product { get; set; }
        public Nullable<System.DateTime> StartCoverDate { get; set; }
        public Nullable<System.DateTime> PortfolioPeriod { get; set; }
        public Nullable<int> ApplicationStatusId { get; set; }
        public string ApplicationStatus { get; set; }
        public Nullable<int> ApplicationUnderwriteStatusId { get; set; }
        public string ApplicationUnderwriteStatus { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<int> CancelCauseId { get; set; }
        public string CancelCause { get; set; }
        public string CancelRemark { get; set; }
        public string CustName { get; set; }
        public string CustBuildingName { get; set; }
        public string CustSubDistrictId { get; set; }
        public string CustSubDistrict { get; set; }
        public string CustDistrictId { get; set; }
        public string CustDistrict { get; set; }
        public string CustProvinceId { get; set; }
        public string CustProvince { get; set; }
        public string PayerName { get; set; }
        public string PayerBuildingName { get; set; }
        public string PayerSubDistrictId { get; set; }
        public string PayerSubDistrict { get; set; }
        public string PayerDistrictId { get; set; }
        public string PayerDistrict { get; set; }
        public string PayerProvinceId { get; set; }
        public string PayerProvince { get; set; }
        public Nullable<int> PayerBranchId { get; set; }
        public string PayerBranchCode { get; set; }
        public string PayerBranch { get; set; }
        public Nullable<int> PayerStudyAreaId { get; set; }
        public string PayerStudyAreaCode { get; set; }
        public string PayerStudyArea { get; set; }
        public Nullable<int> SaleEmployeeId { get; set; }
        public string SaleCode { get; set; }
        public string SaleName { get; set; }
        public string PolicyNo { get; set; }
        public Nullable<System.DateTime> PolicyStart { get; set; }
        public Nullable<System.DateTime> PolicyEnd { get; set; }
        public Nullable<int> MonthPerPolicy { get; set; }
        public Nullable<double> PolicyPremiumDebt { get; set; }
        public Nullable<double> PolicyPremiumReceive { get; set; }
    }
}
