//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSCriticalIllness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Covid_Short
    {
        public int CovidApplicationId { get; set; }
        public string CovidApplicationCode { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ProductCode { get; set; }
        public string Product { get; set; }
        public Nullable<double> PremiumPerPolicy { get; set; }
        public string CustTitle { get; set; }
        public string CustFirstName { get; set; }
        public string CustLastName { get; set; }
        public Nullable<int> CovidApplicationStatusId { get; set; }
        public string CovidApplicationStatus { get; set; }
        public string InsuredCompany_id { get; set; }
        public string CshPeriodTypeID { get; set; }
        public Nullable<System.DateTime> StartCoverDate { get; set; }
        public Nullable<System.DateTime> EndCoverDate { get; set; }
        public string SubDistrictId { get; set; }
        public string xPeriod { get; set; }
        public Nullable<System.DateTime> PeriodStart { get; set; }
        public Nullable<System.DateTime> PeriodEnd { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string SaleId { get; set; }
    }
}
