//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSCommissionDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_ClaimHouse
    {
        public int Id { get; set; }
        public Nullable<int> Period_Id { get; set; }
        public string AppID { get; set; }
        public string CustomerName { get; set; }
        public string PaidCode { get; set; }
        public string BranchName { get; set; }
        public string EmpCodeApprove { get; set; }
        public string EmpNameApprove { get; set; }
        public Nullable<int> ClaimRequestTotal { get; set; }
        public Nullable<int> ClaimApproveTotal { get; set; }
        public Nullable<System.DateTime> PayClaimDate { get; set; }
    }
}
