//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileParameter
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalculationPlan
    {
        public int Id { get; set; }
        public Nullable<int> PlanTemplateId { get; set; }
        public Nullable<int> ParameterId { get; set; }
        public Nullable<double> CalculatedOrder { get; set; }
    }
}
