//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileParameter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ranking
    {
        public int RankingId { get; set; }
        public string Ranking1 { get; set; }
        public string Remark { get; set; }
        public string ProductTypeCode { get; set; }
        public Nullable<int> ClassId { get; set; }
    }
}
