//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileParameter
{
    using System;
    using System.Collections.Generic;
    
    public partial class StgApplication
    {
        public int Id { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public string ApplicationId { get; set; }
        public string SaleId { get; set; }
        public string CarId { get; set; }
        public string BranchId { get; set; }
        public string TeamId { get; set; }
        public string StatusId { get; set; }
        public Nullable<System.DateTime> StartCoverDate { get; set; }
        public Nullable<System.DateTime> EndCoverDate { get; set; }
        public Nullable<double> Premium { get; set; }
        public string ProductGroupId { get; set; }
        public string UDWStatusId { get; set; }
        public string CancleCauseId { get; set; }
        public string PayerBranchId { get; set; }
        public Nullable<System.DateTime> PortfolioPeriod { get; set; }
    }
}
