//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSConvertFile.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCenterAccount
    {
        public int CostCenterAccountID { get; set; }
        public string CostCenterAccountCode { get; set; }
        public string CostCenterAccountDetail { get; set; }
        public string DeptType { get; set; }
        public string IsActive { get; set; }
    }
}
